// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_laptop_service.proto

package com.protos.learn.sid;

public interface CreateLaptopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protos.learn.CreateLaptopRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.protos.learn.Laptop laptop = 1;</code>
   */
  boolean hasLaptop();
  /**
   * <code>.com.protos.learn.Laptop laptop = 1;</code>
   */
  com.protos.learn.sid.TestLaptopMessage.Laptop getLaptop();
  /**
   * <code>.com.protos.learn.Laptop laptop = 1;</code>
   */
  com.protos.learn.sid.TestLaptopMessage.LaptopOrBuilder getLaptopOrBuilder();
}
