// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_laptop_service.proto

package com.protos.learn.sid;

public interface CreateLaptopResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.protos.learn.CreateLaptopResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
