// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_processor_message.proto

package com.protos.learn.sid;

public final class TestProcessorMessage {
  private TestProcessorMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CPUOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.learn.CPU)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string brand = 1;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>uint32 number_cores = 3;</code>
     */
    int getNumberCores();

    /**
     * <code>uint32 number_threads = 4;</code>
     */
    int getNumberThreads();

    /**
     * <code>float min_ghz = 5;</code>
     */
    float getMinGhz();

    /**
     * <code>double max_ghz = 6;</code>
     */
    double getMaxGhz();
  }
  /**
   * Protobuf type {@code com.protos.learn.CPU}
   */
  public  static final class CPU extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.learn.CPU)
      CPUOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CPU.newBuilder() to construct.
    private CPU(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CPU() {
      brand_ = "";
      name_ = "";
      numberCores_ = 0;
      numberThreads_ = 0;
      minGhz_ = 0F;
      maxGhz_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CPU(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 24: {

              numberCores_ = input.readUInt32();
              break;
            }
            case 32: {

              numberThreads_ = input.readUInt32();
              break;
            }
            case 45: {

              minGhz_ = input.readFloat();
              break;
            }
            case 49: {

              maxGhz_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_CPU_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_CPU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.learn.sid.TestProcessorMessage.CPU.class, com.protos.learn.sid.TestProcessorMessage.CPU.Builder.class);
    }

    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 1;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_CORES_FIELD_NUMBER = 3;
    private int numberCores_;
    /**
     * <code>uint32 number_cores = 3;</code>
     */
    public int getNumberCores() {
      return numberCores_;
    }

    public static final int NUMBER_THREADS_FIELD_NUMBER = 4;
    private int numberThreads_;
    /**
     * <code>uint32 number_threads = 4;</code>
     */
    public int getNumberThreads() {
      return numberThreads_;
    }

    public static final int MIN_GHZ_FIELD_NUMBER = 5;
    private float minGhz_;
    /**
     * <code>float min_ghz = 5;</code>
     */
    public float getMinGhz() {
      return minGhz_;
    }

    public static final int MAX_GHZ_FIELD_NUMBER = 6;
    private double maxGhz_;
    /**
     * <code>double max_ghz = 6;</code>
     */
    public double getMaxGhz() {
      return maxGhz_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (numberCores_ != 0) {
        output.writeUInt32(3, numberCores_);
      }
      if (numberThreads_ != 0) {
        output.writeUInt32(4, numberThreads_);
      }
      if (minGhz_ != 0F) {
        output.writeFloat(5, minGhz_);
      }
      if (maxGhz_ != 0D) {
        output.writeDouble(6, maxGhz_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (numberCores_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, numberCores_);
      }
      if (numberThreads_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, numberThreads_);
      }
      if (minGhz_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, minGhz_);
      }
      if (maxGhz_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(6, maxGhz_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.learn.sid.TestProcessorMessage.CPU)) {
        return super.equals(obj);
      }
      com.protos.learn.sid.TestProcessorMessage.CPU other = (com.protos.learn.sid.TestProcessorMessage.CPU) obj;

      boolean result = true;
      result = result && getBrand()
          .equals(other.getBrand());
      result = result && getName()
          .equals(other.getName());
      result = result && (getNumberCores()
          == other.getNumberCores());
      result = result && (getNumberThreads()
          == other.getNumberThreads());
      result = result && (
          java.lang.Float.floatToIntBits(getMinGhz())
          == java.lang.Float.floatToIntBits(
              other.getMinGhz()));
      result = result && (
          java.lang.Double.doubleToLongBits(getMaxGhz())
          == java.lang.Double.doubleToLongBits(
              other.getMaxGhz()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + NUMBER_CORES_FIELD_NUMBER;
      hash = (53 * hash) + getNumberCores();
      hash = (37 * hash) + NUMBER_THREADS_FIELD_NUMBER;
      hash = (53 * hash) + getNumberThreads();
      hash = (37 * hash) + MIN_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getMinGhz());
      hash = (37 * hash) + MAX_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxGhz()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestProcessorMessage.CPU parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.learn.sid.TestProcessorMessage.CPU prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.learn.CPU}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.learn.CPU)
        com.protos.learn.sid.TestProcessorMessage.CPUOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_CPU_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_CPU_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.learn.sid.TestProcessorMessage.CPU.class, com.protos.learn.sid.TestProcessorMessage.CPU.Builder.class);
      }

      // Construct using com.protos.learn.sid.TestProcessorMessage.CPU.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        brand_ = "";

        name_ = "";

        numberCores_ = 0;

        numberThreads_ = 0;

        minGhz_ = 0F;

        maxGhz_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_CPU_descriptor;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestProcessorMessage.CPU getDefaultInstanceForType() {
        return com.protos.learn.sid.TestProcessorMessage.CPU.getDefaultInstance();
      }

      @java.lang.Override
      public com.protos.learn.sid.TestProcessorMessage.CPU build() {
        com.protos.learn.sid.TestProcessorMessage.CPU result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestProcessorMessage.CPU buildPartial() {
        com.protos.learn.sid.TestProcessorMessage.CPU result = new com.protos.learn.sid.TestProcessorMessage.CPU(this);
        result.brand_ = brand_;
        result.name_ = name_;
        result.numberCores_ = numberCores_;
        result.numberThreads_ = numberThreads_;
        result.minGhz_ = minGhz_;
        result.maxGhz_ = maxGhz_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.learn.sid.TestProcessorMessage.CPU) {
          return mergeFrom((com.protos.learn.sid.TestProcessorMessage.CPU)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.learn.sid.TestProcessorMessage.CPU other) {
        if (other == com.protos.learn.sid.TestProcessorMessage.CPU.getDefaultInstance()) return this;
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getNumberCores() != 0) {
          setNumberCores(other.getNumberCores());
        }
        if (other.getNumberThreads() != 0) {
          setNumberThreads(other.getNumberThreads());
        }
        if (other.getMinGhz() != 0F) {
          setMinGhz(other.getMinGhz());
        }
        if (other.getMaxGhz() != 0D) {
          setMaxGhz(other.getMaxGhz());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.learn.sid.TestProcessorMessage.CPU parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.learn.sid.TestProcessorMessage.CPU) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 1;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private int numberCores_ ;
      /**
       * <code>uint32 number_cores = 3;</code>
       */
      public int getNumberCores() {
        return numberCores_;
      }
      /**
       * <code>uint32 number_cores = 3;</code>
       */
      public Builder setNumberCores(int value) {
        
        numberCores_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_cores = 3;</code>
       */
      public Builder clearNumberCores() {
        
        numberCores_ = 0;
        onChanged();
        return this;
      }

      private int numberThreads_ ;
      /**
       * <code>uint32 number_threads = 4;</code>
       */
      public int getNumberThreads() {
        return numberThreads_;
      }
      /**
       * <code>uint32 number_threads = 4;</code>
       */
      public Builder setNumberThreads(int value) {
        
        numberThreads_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 number_threads = 4;</code>
       */
      public Builder clearNumberThreads() {
        
        numberThreads_ = 0;
        onChanged();
        return this;
      }

      private float minGhz_ ;
      /**
       * <code>float min_ghz = 5;</code>
       */
      public float getMinGhz() {
        return minGhz_;
      }
      /**
       * <code>float min_ghz = 5;</code>
       */
      public Builder setMinGhz(float value) {
        
        minGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float min_ghz = 5;</code>
       */
      public Builder clearMinGhz() {
        
        minGhz_ = 0F;
        onChanged();
        return this;
      }

      private double maxGhz_ ;
      /**
       * <code>double max_ghz = 6;</code>
       */
      public double getMaxGhz() {
        return maxGhz_;
      }
      /**
       * <code>double max_ghz = 6;</code>
       */
      public Builder setMaxGhz(double value) {
        
        maxGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double max_ghz = 6;</code>
       */
      public Builder clearMaxGhz() {
        
        maxGhz_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protos.learn.CPU)
    }

    // @@protoc_insertion_point(class_scope:com.protos.learn.CPU)
    private static final com.protos.learn.sid.TestProcessorMessage.CPU DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.learn.sid.TestProcessorMessage.CPU();
    }

    public static com.protos.learn.sid.TestProcessorMessage.CPU getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CPU>
        PARSER = new com.google.protobuf.AbstractParser<CPU>() {
      @java.lang.Override
      public CPU parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CPU(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CPU> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CPU> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protos.learn.sid.TestProcessorMessage.CPU getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GPUOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.learn.GPU)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string brand = 1;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 1;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double min_ghz = 3;</code>
     */
    double getMinGhz();

    /**
     * <code>double max_ghz = 4;</code>
     */
    double getMaxGhz();

    /**
     * <code>.com.protos.learn.Memory memory = 5;</code>
     */
    boolean hasMemory();
    /**
     * <code>.com.protos.learn.Memory memory = 5;</code>
     */
    com.protos.learn.sid.TestMemoryMessage.Memory getMemory();
    /**
     * <code>.com.protos.learn.Memory memory = 5;</code>
     */
    com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getMemoryOrBuilder();
  }
  /**
   * Protobuf type {@code com.protos.learn.GPU}
   */
  public  static final class GPU extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.learn.GPU)
      GPUOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use GPU.newBuilder() to construct.
    private GPU(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GPU() {
      brand_ = "";
      name_ = "";
      minGhz_ = 0D;
      maxGhz_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GPU(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 25: {

              minGhz_ = input.readDouble();
              break;
            }
            case 33: {

              maxGhz_ = input.readDouble();
              break;
            }
            case 42: {
              com.protos.learn.sid.TestMemoryMessage.Memory.Builder subBuilder = null;
              if (memory_ != null) {
                subBuilder = memory_.toBuilder();
              }
              memory_ = input.readMessage(com.protos.learn.sid.TestMemoryMessage.Memory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(memory_);
                memory_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_GPU_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_GPU_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.learn.sid.TestProcessorMessage.GPU.class, com.protos.learn.sid.TestProcessorMessage.GPU.Builder.class);
    }

    public static final int BRAND_FIELD_NUMBER = 1;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 1;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MIN_GHZ_FIELD_NUMBER = 3;
    private double minGhz_;
    /**
     * <code>double min_ghz = 3;</code>
     */
    public double getMinGhz() {
      return minGhz_;
    }

    public static final int MAX_GHZ_FIELD_NUMBER = 4;
    private double maxGhz_;
    /**
     * <code>double max_ghz = 4;</code>
     */
    public double getMaxGhz() {
      return maxGhz_;
    }

    public static final int MEMORY_FIELD_NUMBER = 5;
    private com.protos.learn.sid.TestMemoryMessage.Memory memory_;
    /**
     * <code>.com.protos.learn.Memory memory = 5;</code>
     */
    public boolean hasMemory() {
      return memory_ != null;
    }
    /**
     * <code>.com.protos.learn.Memory memory = 5;</code>
     */
    public com.protos.learn.sid.TestMemoryMessage.Memory getMemory() {
      return memory_ == null ? com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : memory_;
    }
    /**
     * <code>.com.protos.learn.Memory memory = 5;</code>
     */
    public com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
      return getMemory();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, brand_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (minGhz_ != 0D) {
        output.writeDouble(3, minGhz_);
      }
      if (maxGhz_ != 0D) {
        output.writeDouble(4, maxGhz_);
      }
      if (memory_ != null) {
        output.writeMessage(5, getMemory());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, brand_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (minGhz_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, minGhz_);
      }
      if (maxGhz_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, maxGhz_);
      }
      if (memory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getMemory());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.learn.sid.TestProcessorMessage.GPU)) {
        return super.equals(obj);
      }
      com.protos.learn.sid.TestProcessorMessage.GPU other = (com.protos.learn.sid.TestProcessorMessage.GPU) obj;

      boolean result = true;
      result = result && getBrand()
          .equals(other.getBrand());
      result = result && getName()
          .equals(other.getName());
      result = result && (
          java.lang.Double.doubleToLongBits(getMinGhz())
          == java.lang.Double.doubleToLongBits(
              other.getMinGhz()));
      result = result && (
          java.lang.Double.doubleToLongBits(getMaxGhz())
          == java.lang.Double.doubleToLongBits(
              other.getMaxGhz()));
      result = result && (hasMemory() == other.hasMemory());
      if (hasMemory()) {
        result = result && getMemory()
            .equals(other.getMemory());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + MIN_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMinGhz()));
      hash = (37 * hash) + MAX_GHZ_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getMaxGhz()));
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + getMemory().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestProcessorMessage.GPU parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.learn.sid.TestProcessorMessage.GPU prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.learn.GPU}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.learn.GPU)
        com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_GPU_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_GPU_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.learn.sid.TestProcessorMessage.GPU.class, com.protos.learn.sid.TestProcessorMessage.GPU.Builder.class);
      }

      // Construct using com.protos.learn.sid.TestProcessorMessage.GPU.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        brand_ = "";

        name_ = "";

        minGhz_ = 0D;

        maxGhz_ = 0D;

        if (memoryBuilder_ == null) {
          memory_ = null;
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.learn.sid.TestProcessorMessage.internal_static_com_protos_learn_GPU_descriptor;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestProcessorMessage.GPU getDefaultInstanceForType() {
        return com.protos.learn.sid.TestProcessorMessage.GPU.getDefaultInstance();
      }

      @java.lang.Override
      public com.protos.learn.sid.TestProcessorMessage.GPU build() {
        com.protos.learn.sid.TestProcessorMessage.GPU result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestProcessorMessage.GPU buildPartial() {
        com.protos.learn.sid.TestProcessorMessage.GPU result = new com.protos.learn.sid.TestProcessorMessage.GPU(this);
        result.brand_ = brand_;
        result.name_ = name_;
        result.minGhz_ = minGhz_;
        result.maxGhz_ = maxGhz_;
        if (memoryBuilder_ == null) {
          result.memory_ = memory_;
        } else {
          result.memory_ = memoryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.learn.sid.TestProcessorMessage.GPU) {
          return mergeFrom((com.protos.learn.sid.TestProcessorMessage.GPU)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.learn.sid.TestProcessorMessage.GPU other) {
        if (other == com.protos.learn.sid.TestProcessorMessage.GPU.getDefaultInstance()) return this;
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.getMinGhz() != 0D) {
          setMinGhz(other.getMinGhz());
        }
        if (other.getMaxGhz() != 0D) {
          setMaxGhz(other.getMaxGhz());
        }
        if (other.hasMemory()) {
          mergeMemory(other.getMemory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.learn.sid.TestProcessorMessage.GPU parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.learn.sid.TestProcessorMessage.GPU) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 1;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 1;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 1;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private double minGhz_ ;
      /**
       * <code>double min_ghz = 3;</code>
       */
      public double getMinGhz() {
        return minGhz_;
      }
      /**
       * <code>double min_ghz = 3;</code>
       */
      public Builder setMinGhz(double value) {
        
        minGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double min_ghz = 3;</code>
       */
      public Builder clearMinGhz() {
        
        minGhz_ = 0D;
        onChanged();
        return this;
      }

      private double maxGhz_ ;
      /**
       * <code>double max_ghz = 4;</code>
       */
      public double getMaxGhz() {
        return maxGhz_;
      }
      /**
       * <code>double max_ghz = 4;</code>
       */
      public Builder setMaxGhz(double value) {
        
        maxGhz_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double max_ghz = 4;</code>
       */
      public Builder clearMaxGhz() {
        
        maxGhz_ = 0D;
        onChanged();
        return this;
      }

      private com.protos.learn.sid.TestMemoryMessage.Memory memory_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder> memoryBuilder_;
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public boolean hasMemory() {
        return memoryBuilder_ != null || memory_ != null;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.Memory getMemory() {
        if (memoryBuilder_ == null) {
          return memory_ == null ? com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : memory_;
        } else {
          return memoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public Builder setMemory(com.protos.learn.sid.TestMemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          memory_ = value;
          onChanged();
        } else {
          memoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public Builder setMemory(
          com.protos.learn.sid.TestMemoryMessage.Memory.Builder builderForValue) {
        if (memoryBuilder_ == null) {
          memory_ = builderForValue.build();
          onChanged();
        } else {
          memoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public Builder mergeMemory(com.protos.learn.sid.TestMemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (memory_ != null) {
            memory_ =
              com.protos.learn.sid.TestMemoryMessage.Memory.newBuilder(memory_).mergeFrom(value).buildPartial();
          } else {
            memory_ = value;
          }
          onChanged();
        } else {
          memoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public Builder clearMemory() {
        if (memoryBuilder_ == null) {
          memory_ = null;
          onChanged();
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.Memory.Builder getMemoryBuilder() {
        
        onChanged();
        return getMemoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
        if (memoryBuilder_ != null) {
          return memoryBuilder_.getMessageOrBuilder();
        } else {
          return memory_ == null ?
              com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : memory_;
        }
      }
      /**
       * <code>.com.protos.learn.Memory memory = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder> 
          getMemoryFieldBuilder() {
        if (memoryBuilder_ == null) {
          memoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder>(
                  getMemory(),
                  getParentForChildren(),
                  isClean());
          memory_ = null;
        }
        return memoryBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protos.learn.GPU)
    }

    // @@protoc_insertion_point(class_scope:com.protos.learn.GPU)
    private static final com.protos.learn.sid.TestProcessorMessage.GPU DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.learn.sid.TestProcessorMessage.GPU();
    }

    public static com.protos.learn.sid.TestProcessorMessage.GPU getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GPU>
        PARSER = new com.google.protobuf.AbstractParser<GPU>() {
      @java.lang.Override
      public GPU parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new GPU(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GPU> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GPU> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protos.learn.sid.TestProcessorMessage.GPU getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_CPU_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_CPU_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_GPU_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_GPU_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034test_processor_message.proto\022\020com.prot" +
      "os.learn\032\031test_memory_message.proto\"r\n\003C" +
      "PU\022\r\n\005brand\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\024\n\014numbe" +
      "r_cores\030\003 \001(\r\022\026\n\016number_threads\030\004 \001(\r\022\017\n" +
      "\007min_ghz\030\005 \001(\002\022\017\n\007max_ghz\030\006 \001(\001\"n\n\003GPU\022\r" +
      "\n\005brand\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\017\n\007min_ghz\030\003" +
      " \001(\001\022\017\n\007max_ghz\030\004 \001(\001\022(\n\006memory\030\005 \001(\0132\030." +
      "com.protos.learn.MemoryB\026\n\024com.protos.le" +
      "arn.sidb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.learn.sid.TestMemoryMessage.getDescriptor(),
        }, assigner);
    internal_static_com_protos_learn_CPU_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_learn_CPU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_CPU_descriptor,
        new java.lang.String[] { "Brand", "Name", "NumberCores", "NumberThreads", "MinGhz", "MaxGhz", });
    internal_static_com_protos_learn_GPU_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protos_learn_GPU_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_GPU_descriptor,
        new java.lang.String[] { "Brand", "Name", "MinGhz", "MaxGhz", "Memory", });
    com.protos.learn.sid.TestMemoryMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
