// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_laptop_service.proto

package com.protos.learn.sid;

public final class TestLaptopService {
  private TestLaptopService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_CreateLaptopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_CreateLaptopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_CreateLaptopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_CreateLaptopResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031test_laptop_service.proto\022\020com.protos." +
      "learn\032\031test_laptop_message.proto\"?\n\023Crea" +
      "teLaptopRequest\022(\n\006laptop\030\001 \001(\0132\030.com.pr" +
      "otos.learn.Laptop\"\"\n\024CreateLaptopRespons" +
      "e\022\n\n\002id\030\002 \001(\t2p\n\rLaptopService\022_\n\014Create" +
      "Laptop\022%.com.protos.learn.CreateLaptopRe" +
      "quest\032&.com.protos.learn.CreateLaptopRes" +
      "ponse\"\000B\030\n\024com.protos.learn.sidP\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.learn.sid.TestLaptopMessage.getDescriptor(),
        }, assigner);
    internal_static_com_protos_learn_CreateLaptopRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_learn_CreateLaptopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_CreateLaptopRequest_descriptor,
        new java.lang.String[] { "Laptop", });
    internal_static_com_protos_learn_CreateLaptopResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_protos_learn_CreateLaptopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_CreateLaptopResponse_descriptor,
        new java.lang.String[] { "Id", });
    com.protos.learn.sid.TestLaptopMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
