// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_storage_message.proto

package com.protos.learn.sid;

public final class TestStorageMessage {
  private TestStorageMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StorageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.learn.Storage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
     */
    int getDriverValue();
    /**
     * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
     */
    com.protos.learn.sid.TestStorageMessage.Storage.Driver getDriver();

    /**
     * <code>.com.protos.learn.Memory memory = 2;</code>
     */
    boolean hasMemory();
    /**
     * <code>.com.protos.learn.Memory memory = 2;</code>
     */
    com.protos.learn.sid.TestMemoryMessage.Memory getMemory();
    /**
     * <code>.com.protos.learn.Memory memory = 2;</code>
     */
    com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getMemoryOrBuilder();
  }
  /**
   * Protobuf type {@code com.protos.learn.Storage}
   */
  public  static final class Storage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.learn.Storage)
      StorageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Storage.newBuilder() to construct.
    private Storage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Storage() {
      driver_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Storage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              driver_ = rawValue;
              break;
            }
            case 18: {
              com.protos.learn.sid.TestMemoryMessage.Memory.Builder subBuilder = null;
              if (memory_ != null) {
                subBuilder = memory_.toBuilder();
              }
              memory_ = input.readMessage(com.protos.learn.sid.TestMemoryMessage.Memory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(memory_);
                memory_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.learn.sid.TestStorageMessage.internal_static_com_protos_learn_Storage_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.learn.sid.TestStorageMessage.internal_static_com_protos_learn_Storage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.learn.sid.TestStorageMessage.Storage.class, com.protos.learn.sid.TestStorageMessage.Storage.Builder.class);
    }

    /**
     * Protobuf enum {@code com.protos.learn.Storage.Driver}
     */
    public enum Driver
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>HDD = 1;</code>
       */
      HDD(1),
      /**
       * <code>SDD = 2;</code>
       */
      SDD(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>HDD = 1;</code>
       */
      public static final int HDD_VALUE = 1;
      /**
       * <code>SDD = 2;</code>
       */
      public static final int SDD_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Driver valueOf(int value) {
        return forNumber(value);
      }

      public static Driver forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return HDD;
          case 2: return SDD;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Driver>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Driver> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Driver>() {
              public Driver findValueByNumber(int number) {
                return Driver.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.protos.learn.sid.TestStorageMessage.Storage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Driver[] VALUES = values();

      public static Driver valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Driver(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.protos.learn.Storage.Driver)
    }

    public static final int DRIVER_FIELD_NUMBER = 1;
    private int driver_;
    /**
     * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
     */
    public int getDriverValue() {
      return driver_;
    }
    /**
     * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
     */
    public com.protos.learn.sid.TestStorageMessage.Storage.Driver getDriver() {
      @SuppressWarnings("deprecation")
      com.protos.learn.sid.TestStorageMessage.Storage.Driver result = com.protos.learn.sid.TestStorageMessage.Storage.Driver.valueOf(driver_);
      return result == null ? com.protos.learn.sid.TestStorageMessage.Storage.Driver.UNRECOGNIZED : result;
    }

    public static final int MEMORY_FIELD_NUMBER = 2;
    private com.protos.learn.sid.TestMemoryMessage.Memory memory_;
    /**
     * <code>.com.protos.learn.Memory memory = 2;</code>
     */
    public boolean hasMemory() {
      return memory_ != null;
    }
    /**
     * <code>.com.protos.learn.Memory memory = 2;</code>
     */
    public com.protos.learn.sid.TestMemoryMessage.Memory getMemory() {
      return memory_ == null ? com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : memory_;
    }
    /**
     * <code>.com.protos.learn.Memory memory = 2;</code>
     */
    public com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
      return getMemory();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (driver_ != com.protos.learn.sid.TestStorageMessage.Storage.Driver.UNKNOWN.getNumber()) {
        output.writeEnum(1, driver_);
      }
      if (memory_ != null) {
        output.writeMessage(2, getMemory());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (driver_ != com.protos.learn.sid.TestStorageMessage.Storage.Driver.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, driver_);
      }
      if (memory_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMemory());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.learn.sid.TestStorageMessage.Storage)) {
        return super.equals(obj);
      }
      com.protos.learn.sid.TestStorageMessage.Storage other = (com.protos.learn.sid.TestStorageMessage.Storage) obj;

      boolean result = true;
      result = result && driver_ == other.driver_;
      result = result && (hasMemory() == other.hasMemory());
      if (hasMemory()) {
        result = result && getMemory()
            .equals(other.getMemory());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DRIVER_FIELD_NUMBER;
      hash = (53 * hash) + driver_;
      if (hasMemory()) {
        hash = (37 * hash) + MEMORY_FIELD_NUMBER;
        hash = (53 * hash) + getMemory().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestStorageMessage.Storage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.learn.sid.TestStorageMessage.Storage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.learn.Storage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.learn.Storage)
        com.protos.learn.sid.TestStorageMessage.StorageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.learn.sid.TestStorageMessage.internal_static_com_protos_learn_Storage_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.learn.sid.TestStorageMessage.internal_static_com_protos_learn_Storage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.learn.sid.TestStorageMessage.Storage.class, com.protos.learn.sid.TestStorageMessage.Storage.Builder.class);
      }

      // Construct using com.protos.learn.sid.TestStorageMessage.Storage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        driver_ = 0;

        if (memoryBuilder_ == null) {
          memory_ = null;
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.learn.sid.TestStorageMessage.internal_static_com_protos_learn_Storage_descriptor;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestStorageMessage.Storage getDefaultInstanceForType() {
        return com.protos.learn.sid.TestStorageMessage.Storage.getDefaultInstance();
      }

      @java.lang.Override
      public com.protos.learn.sid.TestStorageMessage.Storage build() {
        com.protos.learn.sid.TestStorageMessage.Storage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestStorageMessage.Storage buildPartial() {
        com.protos.learn.sid.TestStorageMessage.Storage result = new com.protos.learn.sid.TestStorageMessage.Storage(this);
        result.driver_ = driver_;
        if (memoryBuilder_ == null) {
          result.memory_ = memory_;
        } else {
          result.memory_ = memoryBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.learn.sid.TestStorageMessage.Storage) {
          return mergeFrom((com.protos.learn.sid.TestStorageMessage.Storage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.learn.sid.TestStorageMessage.Storage other) {
        if (other == com.protos.learn.sid.TestStorageMessage.Storage.getDefaultInstance()) return this;
        if (other.driver_ != 0) {
          setDriverValue(other.getDriverValue());
        }
        if (other.hasMemory()) {
          mergeMemory(other.getMemory());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.learn.sid.TestStorageMessage.Storage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.learn.sid.TestStorageMessage.Storage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int driver_ = 0;
      /**
       * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
       */
      public int getDriverValue() {
        return driver_;
      }
      /**
       * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
       */
      public Builder setDriverValue(int value) {
        driver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
       */
      public com.protos.learn.sid.TestStorageMessage.Storage.Driver getDriver() {
        @SuppressWarnings("deprecation")
        com.protos.learn.sid.TestStorageMessage.Storage.Driver result = com.protos.learn.sid.TestStorageMessage.Storage.Driver.valueOf(driver_);
        return result == null ? com.protos.learn.sid.TestStorageMessage.Storage.Driver.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
       */
      public Builder setDriver(com.protos.learn.sid.TestStorageMessage.Storage.Driver value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        driver_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.protos.learn.Storage.Driver driver = 1;</code>
       */
      public Builder clearDriver() {
        
        driver_ = 0;
        onChanged();
        return this;
      }

      private com.protos.learn.sid.TestMemoryMessage.Memory memory_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder> memoryBuilder_;
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public boolean hasMemory() {
        return memoryBuilder_ != null || memory_ != null;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.Memory getMemory() {
        if (memoryBuilder_ == null) {
          return memory_ == null ? com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : memory_;
        } else {
          return memoryBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public Builder setMemory(com.protos.learn.sid.TestMemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          memory_ = value;
          onChanged();
        } else {
          memoryBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public Builder setMemory(
          com.protos.learn.sid.TestMemoryMessage.Memory.Builder builderForValue) {
        if (memoryBuilder_ == null) {
          memory_ = builderForValue.build();
          onChanged();
        } else {
          memoryBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public Builder mergeMemory(com.protos.learn.sid.TestMemoryMessage.Memory value) {
        if (memoryBuilder_ == null) {
          if (memory_ != null) {
            memory_ =
              com.protos.learn.sid.TestMemoryMessage.Memory.newBuilder(memory_).mergeFrom(value).buildPartial();
          } else {
            memory_ = value;
          }
          onChanged();
        } else {
          memoryBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public Builder clearMemory() {
        if (memoryBuilder_ == null) {
          memory_ = null;
          onChanged();
        } else {
          memory_ = null;
          memoryBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.Memory.Builder getMemoryBuilder() {
        
        onChanged();
        return getMemoryFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getMemoryOrBuilder() {
        if (memoryBuilder_ != null) {
          return memoryBuilder_.getMessageOrBuilder();
        } else {
          return memory_ == null ?
              com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : memory_;
        }
      }
      /**
       * <code>.com.protos.learn.Memory memory = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder> 
          getMemoryFieldBuilder() {
        if (memoryBuilder_ == null) {
          memoryBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder>(
                  getMemory(),
                  getParentForChildren(),
                  isClean());
          memory_ = null;
        }
        return memoryBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protos.learn.Storage)
    }

    // @@protoc_insertion_point(class_scope:com.protos.learn.Storage)
    private static final com.protos.learn.sid.TestStorageMessage.Storage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.learn.sid.TestStorageMessage.Storage();
    }

    public static com.protos.learn.sid.TestStorageMessage.Storage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Storage>
        PARSER = new com.google.protobuf.AbstractParser<Storage>() {
      @java.lang.Override
      public Storage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Storage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Storage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Storage> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protos.learn.sid.TestStorageMessage.Storage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_Storage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_Storage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032test_storage_message.proto\022\020com.protos" +
      ".learn\032\031test_memory_message.proto\"\216\001\n\007St" +
      "orage\0220\n\006driver\030\001 \001(\0162 .com.protos.learn" +
      ".Storage.Driver\022(\n\006memory\030\002 \001(\0132\030.com.pr" +
      "otos.learn.Memory\"\'\n\006Driver\022\013\n\007UNKNOWN\020\000" +
      "\022\007\n\003HDD\020\001\022\007\n\003SDD\020\002B\026\n\024com.protos.learn.s" +
      "idb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.learn.sid.TestMemoryMessage.getDescriptor(),
        }, assigner);
    internal_static_com_protos_learn_Storage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_learn_Storage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_Storage_descriptor,
        new java.lang.String[] { "Driver", "Memory", });
    com.protos.learn.sid.TestMemoryMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
