// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_laptop_message.proto

package com.protos.learn.sid;

public final class TestLaptopMessage {
  private TestLaptopMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface LaptopOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.learn.Laptop)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string brand = 2;</code>
     */
    java.lang.String getBrand();
    /**
     * <code>string brand = 2;</code>
     */
    com.google.protobuf.ByteString
        getBrandBytes();

    /**
     * <code>string name = 3;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 3;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>.com.protos.learn.CPU cpu = 4;</code>
     */
    boolean hasCpu();
    /**
     * <code>.com.protos.learn.CPU cpu = 4;</code>
     */
    com.protos.learn.sid.TestProcessorMessage.CPU getCpu();
    /**
     * <code>.com.protos.learn.CPU cpu = 4;</code>
     */
    com.protos.learn.sid.TestProcessorMessage.CPUOrBuilder getCpuOrBuilder();

    /**
     * <code>.com.protos.learn.Memory ram = 5;</code>
     */
    boolean hasRam();
    /**
     * <code>.com.protos.learn.Memory ram = 5;</code>
     */
    com.protos.learn.sid.TestMemoryMessage.Memory getRam();
    /**
     * <code>.com.protos.learn.Memory ram = 5;</code>
     */
    com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getRamOrBuilder();

    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    java.util.List<com.protos.learn.sid.TestProcessorMessage.GPU> 
        getGpusList();
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    com.protos.learn.sid.TestProcessorMessage.GPU getGpus(int index);
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    int getGpusCount();
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    java.util.List<? extends com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder> 
        getGpusOrBuilderList();
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder getGpusOrBuilder(
        int index);

    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    java.util.List<com.protos.learn.sid.TestStorageMessage.Storage> 
        getStoragesList();
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    com.protos.learn.sid.TestStorageMessage.Storage getStorages(int index);
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    int getStoragesCount();
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    java.util.List<? extends com.protos.learn.sid.TestStorageMessage.StorageOrBuilder> 
        getStoragesOrBuilderList();
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    com.protos.learn.sid.TestStorageMessage.StorageOrBuilder getStoragesOrBuilder(
        int index);

    /**
     * <code>.com.protos.learn.Screen screen = 8;</code>
     */
    boolean hasScreen();
    /**
     * <code>.com.protos.learn.Screen screen = 8;</code>
     */
    com.protos.learn.sid.TestScreenMessage.Screen getScreen();
    /**
     * <code>.com.protos.learn.Screen screen = 8;</code>
     */
    com.protos.learn.sid.TestScreenMessage.ScreenOrBuilder getScreenOrBuilder();

    /**
     * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
     */
    boolean hasKeyboard();
    /**
     * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
     */
    com.protos.learn.sid.TestKeyboardMessage.Keyboard getKeyboard();
    /**
     * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
     */
    com.protos.learn.sid.TestKeyboardMessage.KeyboardOrBuilder getKeyboardOrBuilder();

    /**
     * <code>double weight_kg = 10;</code>
     */
    double getWeightKg();

    /**
     * <code>double weight_lb = 11;</code>
     */
    double getWeightLb();

    /**
     * <code>double price_usd = 12;</code>
     */
    double getPriceUsd();

    /**
     * <code>uint32 release_year = 13;</code>
     */
    int getReleaseYear();

    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    boolean hasUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    com.google.protobuf.Timestamp getUpdatedAt();
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder();

    public com.protos.learn.sid.TestLaptopMessage.Laptop.WeightCase getWeightCase();
  }
  /**
   * Protobuf type {@code com.protos.learn.Laptop}
   */
  public  static final class Laptop extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.learn.Laptop)
      LaptopOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Laptop.newBuilder() to construct.
    private Laptop(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Laptop() {
      id_ = "";
      brand_ = "";
      name_ = "";
      gpus_ = java.util.Collections.emptyList();
      storages_ = java.util.Collections.emptyList();
      priceUsd_ = 0D;
      releaseYear_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Laptop(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              brand_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 34: {
              com.protos.learn.sid.TestProcessorMessage.CPU.Builder subBuilder = null;
              if (cpu_ != null) {
                subBuilder = cpu_.toBuilder();
              }
              cpu_ = input.readMessage(com.protos.learn.sid.TestProcessorMessage.CPU.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(cpu_);
                cpu_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.protos.learn.sid.TestMemoryMessage.Memory.Builder subBuilder = null;
              if (ram_ != null) {
                subBuilder = ram_.toBuilder();
              }
              ram_ = input.readMessage(com.protos.learn.sid.TestMemoryMessage.Memory.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ram_);
                ram_ = subBuilder.buildPartial();
              }

              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                gpus_ = new java.util.ArrayList<com.protos.learn.sid.TestProcessorMessage.GPU>();
                mutable_bitField0_ |= 0x00000020;
              }
              gpus_.add(
                  input.readMessage(com.protos.learn.sid.TestProcessorMessage.GPU.parser(), extensionRegistry));
              break;
            }
            case 58: {
              if (!((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
                storages_ = new java.util.ArrayList<com.protos.learn.sid.TestStorageMessage.Storage>();
                mutable_bitField0_ |= 0x00000040;
              }
              storages_.add(
                  input.readMessage(com.protos.learn.sid.TestStorageMessage.Storage.parser(), extensionRegistry));
              break;
            }
            case 66: {
              com.protos.learn.sid.TestScreenMessage.Screen.Builder subBuilder = null;
              if (screen_ != null) {
                subBuilder = screen_.toBuilder();
              }
              screen_ = input.readMessage(com.protos.learn.sid.TestScreenMessage.Screen.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(screen_);
                screen_ = subBuilder.buildPartial();
              }

              break;
            }
            case 74: {
              com.protos.learn.sid.TestKeyboardMessage.Keyboard.Builder subBuilder = null;
              if (keyboard_ != null) {
                subBuilder = keyboard_.toBuilder();
              }
              keyboard_ = input.readMessage(com.protos.learn.sid.TestKeyboardMessage.Keyboard.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(keyboard_);
                keyboard_ = subBuilder.buildPartial();
              }

              break;
            }
            case 81: {
              weightCase_ = 10;
              weight_ = input.readDouble();
              break;
            }
            case 89: {
              weightCase_ = 11;
              weight_ = input.readDouble();
              break;
            }
            case 97: {

              priceUsd_ = input.readDouble();
              break;
            }
            case 104: {

              releaseYear_ = input.readUInt32();
              break;
            }
            case 114: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (updatedAt_ != null) {
                subBuilder = updatedAt_.toBuilder();
              }
              updatedAt_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(updatedAt_);
                updatedAt_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          gpus_ = java.util.Collections.unmodifiableList(gpus_);
        }
        if (((mutable_bitField0_ & 0x00000040) == 0x00000040)) {
          storages_ = java.util.Collections.unmodifiableList(storages_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.learn.sid.TestLaptopMessage.internal_static_com_protos_learn_Laptop_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.learn.sid.TestLaptopMessage.internal_static_com_protos_learn_Laptop_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.learn.sid.TestLaptopMessage.Laptop.class, com.protos.learn.sid.TestLaptopMessage.Laptop.Builder.class);
    }

    private int bitField0_;
    private int weightCase_ = 0;
    private java.lang.Object weight_;
    public enum WeightCase
        implements com.google.protobuf.Internal.EnumLite {
      WEIGHT_KG(10),
      WEIGHT_LB(11),
      WEIGHT_NOT_SET(0);
      private final int value;
      private WeightCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static WeightCase valueOf(int value) {
        return forNumber(value);
      }

      public static WeightCase forNumber(int value) {
        switch (value) {
          case 10: return WEIGHT_KG;
          case 11: return WEIGHT_LB;
          case 0: return WEIGHT_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public WeightCase
    getWeightCase() {
      return WeightCase.forNumber(
          weightCase_);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BRAND_FIELD_NUMBER = 2;
    private volatile java.lang.Object brand_;
    /**
     * <code>string brand = 2;</code>
     */
    public java.lang.String getBrand() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        brand_ = s;
        return s;
      }
    }
    /**
     * <code>string brand = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBrandBytes() {
      java.lang.Object ref = brand_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        brand_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 3;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPU_FIELD_NUMBER = 4;
    private com.protos.learn.sid.TestProcessorMessage.CPU cpu_;
    /**
     * <code>.com.protos.learn.CPU cpu = 4;</code>
     */
    public boolean hasCpu() {
      return cpu_ != null;
    }
    /**
     * <code>.com.protos.learn.CPU cpu = 4;</code>
     */
    public com.protos.learn.sid.TestProcessorMessage.CPU getCpu() {
      return cpu_ == null ? com.protos.learn.sid.TestProcessorMessage.CPU.getDefaultInstance() : cpu_;
    }
    /**
     * <code>.com.protos.learn.CPU cpu = 4;</code>
     */
    public com.protos.learn.sid.TestProcessorMessage.CPUOrBuilder getCpuOrBuilder() {
      return getCpu();
    }

    public static final int RAM_FIELD_NUMBER = 5;
    private com.protos.learn.sid.TestMemoryMessage.Memory ram_;
    /**
     * <code>.com.protos.learn.Memory ram = 5;</code>
     */
    public boolean hasRam() {
      return ram_ != null;
    }
    /**
     * <code>.com.protos.learn.Memory ram = 5;</code>
     */
    public com.protos.learn.sid.TestMemoryMessage.Memory getRam() {
      return ram_ == null ? com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : ram_;
    }
    /**
     * <code>.com.protos.learn.Memory ram = 5;</code>
     */
    public com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getRamOrBuilder() {
      return getRam();
    }

    public static final int GPUS_FIELD_NUMBER = 6;
    private java.util.List<com.protos.learn.sid.TestProcessorMessage.GPU> gpus_;
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    public java.util.List<com.protos.learn.sid.TestProcessorMessage.GPU> getGpusList() {
      return gpus_;
    }
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    public java.util.List<? extends com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder> 
        getGpusOrBuilderList() {
      return gpus_;
    }
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    public int getGpusCount() {
      return gpus_.size();
    }
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    public com.protos.learn.sid.TestProcessorMessage.GPU getGpus(int index) {
      return gpus_.get(index);
    }
    /**
     * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
     */
    public com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder getGpusOrBuilder(
        int index) {
      return gpus_.get(index);
    }

    public static final int STORAGES_FIELD_NUMBER = 7;
    private java.util.List<com.protos.learn.sid.TestStorageMessage.Storage> storages_;
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    public java.util.List<com.protos.learn.sid.TestStorageMessage.Storage> getStoragesList() {
      return storages_;
    }
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    public java.util.List<? extends com.protos.learn.sid.TestStorageMessage.StorageOrBuilder> 
        getStoragesOrBuilderList() {
      return storages_;
    }
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    public int getStoragesCount() {
      return storages_.size();
    }
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    public com.protos.learn.sid.TestStorageMessage.Storage getStorages(int index) {
      return storages_.get(index);
    }
    /**
     * <code>repeated .com.protos.learn.Storage storages = 7;</code>
     */
    public com.protos.learn.sid.TestStorageMessage.StorageOrBuilder getStoragesOrBuilder(
        int index) {
      return storages_.get(index);
    }

    public static final int SCREEN_FIELD_NUMBER = 8;
    private com.protos.learn.sid.TestScreenMessage.Screen screen_;
    /**
     * <code>.com.protos.learn.Screen screen = 8;</code>
     */
    public boolean hasScreen() {
      return screen_ != null;
    }
    /**
     * <code>.com.protos.learn.Screen screen = 8;</code>
     */
    public com.protos.learn.sid.TestScreenMessage.Screen getScreen() {
      return screen_ == null ? com.protos.learn.sid.TestScreenMessage.Screen.getDefaultInstance() : screen_;
    }
    /**
     * <code>.com.protos.learn.Screen screen = 8;</code>
     */
    public com.protos.learn.sid.TestScreenMessage.ScreenOrBuilder getScreenOrBuilder() {
      return getScreen();
    }

    public static final int KEYBOARD_FIELD_NUMBER = 9;
    private com.protos.learn.sid.TestKeyboardMessage.Keyboard keyboard_;
    /**
     * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
     */
    public boolean hasKeyboard() {
      return keyboard_ != null;
    }
    /**
     * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
     */
    public com.protos.learn.sid.TestKeyboardMessage.Keyboard getKeyboard() {
      return keyboard_ == null ? com.protos.learn.sid.TestKeyboardMessage.Keyboard.getDefaultInstance() : keyboard_;
    }
    /**
     * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
     */
    public com.protos.learn.sid.TestKeyboardMessage.KeyboardOrBuilder getKeyboardOrBuilder() {
      return getKeyboard();
    }

    public static final int WEIGHT_KG_FIELD_NUMBER = 10;
    /**
     * <code>double weight_kg = 10;</code>
     */
    public double getWeightKg() {
      if (weightCase_ == 10) {
        return (java.lang.Double) weight_;
      }
      return 0D;
    }

    public static final int WEIGHT_LB_FIELD_NUMBER = 11;
    /**
     * <code>double weight_lb = 11;</code>
     */
    public double getWeightLb() {
      if (weightCase_ == 11) {
        return (java.lang.Double) weight_;
      }
      return 0D;
    }

    public static final int PRICE_USD_FIELD_NUMBER = 12;
    private double priceUsd_;
    /**
     * <code>double price_usd = 12;</code>
     */
    public double getPriceUsd() {
      return priceUsd_;
    }

    public static final int RELEASE_YEAR_FIELD_NUMBER = 13;
    private int releaseYear_;
    /**
     * <code>uint32 release_year = 13;</code>
     */
    public int getReleaseYear() {
      return releaseYear_;
    }

    public static final int UPDATED_AT_FIELD_NUMBER = 14;
    private com.google.protobuf.Timestamp updatedAt_;
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    public boolean hasUpdatedAt() {
      return updatedAt_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    public com.google.protobuf.Timestamp getUpdatedAt() {
      return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
    }
    /**
     * <code>.google.protobuf.Timestamp updated_at = 14;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
      return getUpdatedAt();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getBrandBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, brand_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, name_);
      }
      if (cpu_ != null) {
        output.writeMessage(4, getCpu());
      }
      if (ram_ != null) {
        output.writeMessage(5, getRam());
      }
      for (int i = 0; i < gpus_.size(); i++) {
        output.writeMessage(6, gpus_.get(i));
      }
      for (int i = 0; i < storages_.size(); i++) {
        output.writeMessage(7, storages_.get(i));
      }
      if (screen_ != null) {
        output.writeMessage(8, getScreen());
      }
      if (keyboard_ != null) {
        output.writeMessage(9, getKeyboard());
      }
      if (weightCase_ == 10) {
        output.writeDouble(
            10, (double)((java.lang.Double) weight_));
      }
      if (weightCase_ == 11) {
        output.writeDouble(
            11, (double)((java.lang.Double) weight_));
      }
      if (priceUsd_ != 0D) {
        output.writeDouble(12, priceUsd_);
      }
      if (releaseYear_ != 0) {
        output.writeUInt32(13, releaseYear_);
      }
      if (updatedAt_ != null) {
        output.writeMessage(14, getUpdatedAt());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getBrandBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, brand_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, name_);
      }
      if (cpu_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCpu());
      }
      if (ram_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getRam());
      }
      for (int i = 0; i < gpus_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, gpus_.get(i));
      }
      for (int i = 0; i < storages_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, storages_.get(i));
      }
      if (screen_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getScreen());
      }
      if (keyboard_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getKeyboard());
      }
      if (weightCase_ == 10) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              10, (double)((java.lang.Double) weight_));
      }
      if (weightCase_ == 11) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(
              11, (double)((java.lang.Double) weight_));
      }
      if (priceUsd_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(12, priceUsd_);
      }
      if (releaseYear_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(13, releaseYear_);
      }
      if (updatedAt_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getUpdatedAt());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.learn.sid.TestLaptopMessage.Laptop)) {
        return super.equals(obj);
      }
      com.protos.learn.sid.TestLaptopMessage.Laptop other = (com.protos.learn.sid.TestLaptopMessage.Laptop) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getBrand()
          .equals(other.getBrand());
      result = result && getName()
          .equals(other.getName());
      result = result && (hasCpu() == other.hasCpu());
      if (hasCpu()) {
        result = result && getCpu()
            .equals(other.getCpu());
      }
      result = result && (hasRam() == other.hasRam());
      if (hasRam()) {
        result = result && getRam()
            .equals(other.getRam());
      }
      result = result && getGpusList()
          .equals(other.getGpusList());
      result = result && getStoragesList()
          .equals(other.getStoragesList());
      result = result && (hasScreen() == other.hasScreen());
      if (hasScreen()) {
        result = result && getScreen()
            .equals(other.getScreen());
      }
      result = result && (hasKeyboard() == other.hasKeyboard());
      if (hasKeyboard()) {
        result = result && getKeyboard()
            .equals(other.getKeyboard());
      }
      result = result && (
          java.lang.Double.doubleToLongBits(getPriceUsd())
          == java.lang.Double.doubleToLongBits(
              other.getPriceUsd()));
      result = result && (getReleaseYear()
          == other.getReleaseYear());
      result = result && (hasUpdatedAt() == other.hasUpdatedAt());
      if (hasUpdatedAt()) {
        result = result && getUpdatedAt()
            .equals(other.getUpdatedAt());
      }
      result = result && getWeightCase().equals(
          other.getWeightCase());
      if (!result) return false;
      switch (weightCase_) {
        case 10:
          result = result && (
              java.lang.Double.doubleToLongBits(getWeightKg())
              == java.lang.Double.doubleToLongBits(
                  other.getWeightKg()));
          break;
        case 11:
          result = result && (
              java.lang.Double.doubleToLongBits(getWeightLb())
              == java.lang.Double.doubleToLongBits(
                  other.getWeightLb()));
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + BRAND_FIELD_NUMBER;
      hash = (53 * hash) + getBrand().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (hasCpu()) {
        hash = (37 * hash) + CPU_FIELD_NUMBER;
        hash = (53 * hash) + getCpu().hashCode();
      }
      if (hasRam()) {
        hash = (37 * hash) + RAM_FIELD_NUMBER;
        hash = (53 * hash) + getRam().hashCode();
      }
      if (getGpusCount() > 0) {
        hash = (37 * hash) + GPUS_FIELD_NUMBER;
        hash = (53 * hash) + getGpusList().hashCode();
      }
      if (getStoragesCount() > 0) {
        hash = (37 * hash) + STORAGES_FIELD_NUMBER;
        hash = (53 * hash) + getStoragesList().hashCode();
      }
      if (hasScreen()) {
        hash = (37 * hash) + SCREEN_FIELD_NUMBER;
        hash = (53 * hash) + getScreen().hashCode();
      }
      if (hasKeyboard()) {
        hash = (37 * hash) + KEYBOARD_FIELD_NUMBER;
        hash = (53 * hash) + getKeyboard().hashCode();
      }
      hash = (37 * hash) + PRICE_USD_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getPriceUsd()));
      hash = (37 * hash) + RELEASE_YEAR_FIELD_NUMBER;
      hash = (53 * hash) + getReleaseYear();
      if (hasUpdatedAt()) {
        hash = (37 * hash) + UPDATED_AT_FIELD_NUMBER;
        hash = (53 * hash) + getUpdatedAt().hashCode();
      }
      switch (weightCase_) {
        case 10:
          hash = (37 * hash) + WEIGHT_KG_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getWeightKg()));
          break;
        case 11:
          hash = (37 * hash) + WEIGHT_LB_FIELD_NUMBER;
          hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
              java.lang.Double.doubleToLongBits(getWeightLb()));
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestLaptopMessage.Laptop parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.learn.sid.TestLaptopMessage.Laptop prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.learn.Laptop}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.learn.Laptop)
        com.protos.learn.sid.TestLaptopMessage.LaptopOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.learn.sid.TestLaptopMessage.internal_static_com_protos_learn_Laptop_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.learn.sid.TestLaptopMessage.internal_static_com_protos_learn_Laptop_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.learn.sid.TestLaptopMessage.Laptop.class, com.protos.learn.sid.TestLaptopMessage.Laptop.Builder.class);
      }

      // Construct using com.protos.learn.sid.TestLaptopMessage.Laptop.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getGpusFieldBuilder();
          getStoragesFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";

        brand_ = "";

        name_ = "";

        if (cpuBuilder_ == null) {
          cpu_ = null;
        } else {
          cpu_ = null;
          cpuBuilder_ = null;
        }
        if (ramBuilder_ == null) {
          ram_ = null;
        } else {
          ram_ = null;
          ramBuilder_ = null;
        }
        if (gpusBuilder_ == null) {
          gpus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          gpusBuilder_.clear();
        }
        if (storagesBuilder_ == null) {
          storages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
        } else {
          storagesBuilder_.clear();
        }
        if (screenBuilder_ == null) {
          screen_ = null;
        } else {
          screen_ = null;
          screenBuilder_ = null;
        }
        if (keyboardBuilder_ == null) {
          keyboard_ = null;
        } else {
          keyboard_ = null;
          keyboardBuilder_ = null;
        }
        priceUsd_ = 0D;

        releaseYear_ = 0;

        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }
        weightCase_ = 0;
        weight_ = null;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.learn.sid.TestLaptopMessage.internal_static_com_protos_learn_Laptop_descriptor;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestLaptopMessage.Laptop getDefaultInstanceForType() {
        return com.protos.learn.sid.TestLaptopMessage.Laptop.getDefaultInstance();
      }

      @java.lang.Override
      public com.protos.learn.sid.TestLaptopMessage.Laptop build() {
        com.protos.learn.sid.TestLaptopMessage.Laptop result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestLaptopMessage.Laptop buildPartial() {
        com.protos.learn.sid.TestLaptopMessage.Laptop result = new com.protos.learn.sid.TestLaptopMessage.Laptop(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.id_ = id_;
        result.brand_ = brand_;
        result.name_ = name_;
        if (cpuBuilder_ == null) {
          result.cpu_ = cpu_;
        } else {
          result.cpu_ = cpuBuilder_.build();
        }
        if (ramBuilder_ == null) {
          result.ram_ = ram_;
        } else {
          result.ram_ = ramBuilder_.build();
        }
        if (gpusBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            gpus_ = java.util.Collections.unmodifiableList(gpus_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.gpus_ = gpus_;
        } else {
          result.gpus_ = gpusBuilder_.build();
        }
        if (storagesBuilder_ == null) {
          if (((bitField0_ & 0x00000040) == 0x00000040)) {
            storages_ = java.util.Collections.unmodifiableList(storages_);
            bitField0_ = (bitField0_ & ~0x00000040);
          }
          result.storages_ = storages_;
        } else {
          result.storages_ = storagesBuilder_.build();
        }
        if (screenBuilder_ == null) {
          result.screen_ = screen_;
        } else {
          result.screen_ = screenBuilder_.build();
        }
        if (keyboardBuilder_ == null) {
          result.keyboard_ = keyboard_;
        } else {
          result.keyboard_ = keyboardBuilder_.build();
        }
        if (weightCase_ == 10) {
          result.weight_ = weight_;
        }
        if (weightCase_ == 11) {
          result.weight_ = weight_;
        }
        result.priceUsd_ = priceUsd_;
        result.releaseYear_ = releaseYear_;
        if (updatedAtBuilder_ == null) {
          result.updatedAt_ = updatedAt_;
        } else {
          result.updatedAt_ = updatedAtBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        result.weightCase_ = weightCase_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.learn.sid.TestLaptopMessage.Laptop) {
          return mergeFrom((com.protos.learn.sid.TestLaptopMessage.Laptop)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.learn.sid.TestLaptopMessage.Laptop other) {
        if (other == com.protos.learn.sid.TestLaptopMessage.Laptop.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getBrand().isEmpty()) {
          brand_ = other.brand_;
          onChanged();
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (other.hasCpu()) {
          mergeCpu(other.getCpu());
        }
        if (other.hasRam()) {
          mergeRam(other.getRam());
        }
        if (gpusBuilder_ == null) {
          if (!other.gpus_.isEmpty()) {
            if (gpus_.isEmpty()) {
              gpus_ = other.gpus_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureGpusIsMutable();
              gpus_.addAll(other.gpus_);
            }
            onChanged();
          }
        } else {
          if (!other.gpus_.isEmpty()) {
            if (gpusBuilder_.isEmpty()) {
              gpusBuilder_.dispose();
              gpusBuilder_ = null;
              gpus_ = other.gpus_;
              bitField0_ = (bitField0_ & ~0x00000020);
              gpusBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getGpusFieldBuilder() : null;
            } else {
              gpusBuilder_.addAllMessages(other.gpus_);
            }
          }
        }
        if (storagesBuilder_ == null) {
          if (!other.storages_.isEmpty()) {
            if (storages_.isEmpty()) {
              storages_ = other.storages_;
              bitField0_ = (bitField0_ & ~0x00000040);
            } else {
              ensureStoragesIsMutable();
              storages_.addAll(other.storages_);
            }
            onChanged();
          }
        } else {
          if (!other.storages_.isEmpty()) {
            if (storagesBuilder_.isEmpty()) {
              storagesBuilder_.dispose();
              storagesBuilder_ = null;
              storages_ = other.storages_;
              bitField0_ = (bitField0_ & ~0x00000040);
              storagesBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStoragesFieldBuilder() : null;
            } else {
              storagesBuilder_.addAllMessages(other.storages_);
            }
          }
        }
        if (other.hasScreen()) {
          mergeScreen(other.getScreen());
        }
        if (other.hasKeyboard()) {
          mergeKeyboard(other.getKeyboard());
        }
        if (other.getPriceUsd() != 0D) {
          setPriceUsd(other.getPriceUsd());
        }
        if (other.getReleaseYear() != 0) {
          setReleaseYear(other.getReleaseYear());
        }
        if (other.hasUpdatedAt()) {
          mergeUpdatedAt(other.getUpdatedAt());
        }
        switch (other.getWeightCase()) {
          case WEIGHT_KG: {
            setWeightKg(other.getWeightKg());
            break;
          }
          case WEIGHT_LB: {
            setWeightLb(other.getWeightLb());
            break;
          }
          case WEIGHT_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.learn.sid.TestLaptopMessage.Laptop parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.learn.sid.TestLaptopMessage.Laptop) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int weightCase_ = 0;
      private java.lang.Object weight_;
      public WeightCase
          getWeightCase() {
        return WeightCase.forNumber(
            weightCase_);
      }

      public Builder clearWeight() {
        weightCase_ = 0;
        weight_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object brand_ = "";
      /**
       * <code>string brand = 2;</code>
       */
      public java.lang.String getBrand() {
        java.lang.Object ref = brand_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          brand_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string brand = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBrandBytes() {
        java.lang.Object ref = brand_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          brand_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string brand = 2;</code>
       */
      public Builder setBrand(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        brand_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 2;</code>
       */
      public Builder clearBrand() {
        
        brand_ = getDefaultInstance().getBrand();
        onChanged();
        return this;
      }
      /**
       * <code>string brand = 2;</code>
       */
      public Builder setBrandBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        brand_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 3;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 3;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private com.protos.learn.sid.TestProcessorMessage.CPU cpu_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestProcessorMessage.CPU, com.protos.learn.sid.TestProcessorMessage.CPU.Builder, com.protos.learn.sid.TestProcessorMessage.CPUOrBuilder> cpuBuilder_;
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public boolean hasCpu() {
        return cpuBuilder_ != null || cpu_ != null;
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.CPU getCpu() {
        if (cpuBuilder_ == null) {
          return cpu_ == null ? com.protos.learn.sid.TestProcessorMessage.CPU.getDefaultInstance() : cpu_;
        } else {
          return cpuBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public Builder setCpu(com.protos.learn.sid.TestProcessorMessage.CPU value) {
        if (cpuBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          cpu_ = value;
          onChanged();
        } else {
          cpuBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public Builder setCpu(
          com.protos.learn.sid.TestProcessorMessage.CPU.Builder builderForValue) {
        if (cpuBuilder_ == null) {
          cpu_ = builderForValue.build();
          onChanged();
        } else {
          cpuBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public Builder mergeCpu(com.protos.learn.sid.TestProcessorMessage.CPU value) {
        if (cpuBuilder_ == null) {
          if (cpu_ != null) {
            cpu_ =
              com.protos.learn.sid.TestProcessorMessage.CPU.newBuilder(cpu_).mergeFrom(value).buildPartial();
          } else {
            cpu_ = value;
          }
          onChanged();
        } else {
          cpuBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public Builder clearCpu() {
        if (cpuBuilder_ == null) {
          cpu_ = null;
          onChanged();
        } else {
          cpu_ = null;
          cpuBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.CPU.Builder getCpuBuilder() {
        
        onChanged();
        return getCpuFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.CPUOrBuilder getCpuOrBuilder() {
        if (cpuBuilder_ != null) {
          return cpuBuilder_.getMessageOrBuilder();
        } else {
          return cpu_ == null ?
              com.protos.learn.sid.TestProcessorMessage.CPU.getDefaultInstance() : cpu_;
        }
      }
      /**
       * <code>.com.protos.learn.CPU cpu = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestProcessorMessage.CPU, com.protos.learn.sid.TestProcessorMessage.CPU.Builder, com.protos.learn.sid.TestProcessorMessage.CPUOrBuilder> 
          getCpuFieldBuilder() {
        if (cpuBuilder_ == null) {
          cpuBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.protos.learn.sid.TestProcessorMessage.CPU, com.protos.learn.sid.TestProcessorMessage.CPU.Builder, com.protos.learn.sid.TestProcessorMessage.CPUOrBuilder>(
                  getCpu(),
                  getParentForChildren(),
                  isClean());
          cpu_ = null;
        }
        return cpuBuilder_;
      }

      private com.protos.learn.sid.TestMemoryMessage.Memory ram_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder> ramBuilder_;
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public boolean hasRam() {
        return ramBuilder_ != null || ram_ != null;
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.Memory getRam() {
        if (ramBuilder_ == null) {
          return ram_ == null ? com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : ram_;
        } else {
          return ramBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public Builder setRam(com.protos.learn.sid.TestMemoryMessage.Memory value) {
        if (ramBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ram_ = value;
          onChanged();
        } else {
          ramBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public Builder setRam(
          com.protos.learn.sid.TestMemoryMessage.Memory.Builder builderForValue) {
        if (ramBuilder_ == null) {
          ram_ = builderForValue.build();
          onChanged();
        } else {
          ramBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public Builder mergeRam(com.protos.learn.sid.TestMemoryMessage.Memory value) {
        if (ramBuilder_ == null) {
          if (ram_ != null) {
            ram_ =
              com.protos.learn.sid.TestMemoryMessage.Memory.newBuilder(ram_).mergeFrom(value).buildPartial();
          } else {
            ram_ = value;
          }
          onChanged();
        } else {
          ramBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public Builder clearRam() {
        if (ramBuilder_ == null) {
          ram_ = null;
          onChanged();
        } else {
          ram_ = null;
          ramBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.Memory.Builder getRamBuilder() {
        
        onChanged();
        return getRamFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      public com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder getRamOrBuilder() {
        if (ramBuilder_ != null) {
          return ramBuilder_.getMessageOrBuilder();
        } else {
          return ram_ == null ?
              com.protos.learn.sid.TestMemoryMessage.Memory.getDefaultInstance() : ram_;
        }
      }
      /**
       * <code>.com.protos.learn.Memory ram = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder> 
          getRamFieldBuilder() {
        if (ramBuilder_ == null) {
          ramBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.protos.learn.sid.TestMemoryMessage.Memory, com.protos.learn.sid.TestMemoryMessage.Memory.Builder, com.protos.learn.sid.TestMemoryMessage.MemoryOrBuilder>(
                  getRam(),
                  getParentForChildren(),
                  isClean());
          ram_ = null;
        }
        return ramBuilder_;
      }

      private java.util.List<com.protos.learn.sid.TestProcessorMessage.GPU> gpus_ =
        java.util.Collections.emptyList();
      private void ensureGpusIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          gpus_ = new java.util.ArrayList<com.protos.learn.sid.TestProcessorMessage.GPU>(gpus_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.learn.sid.TestProcessorMessage.GPU, com.protos.learn.sid.TestProcessorMessage.GPU.Builder, com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder> gpusBuilder_;

      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public java.util.List<com.protos.learn.sid.TestProcessorMessage.GPU> getGpusList() {
        if (gpusBuilder_ == null) {
          return java.util.Collections.unmodifiableList(gpus_);
        } else {
          return gpusBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public int getGpusCount() {
        if (gpusBuilder_ == null) {
          return gpus_.size();
        } else {
          return gpusBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.GPU getGpus(int index) {
        if (gpusBuilder_ == null) {
          return gpus_.get(index);
        } else {
          return gpusBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder setGpus(
          int index, com.protos.learn.sid.TestProcessorMessage.GPU value) {
        if (gpusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpusIsMutable();
          gpus_.set(index, value);
          onChanged();
        } else {
          gpusBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder setGpus(
          int index, com.protos.learn.sid.TestProcessorMessage.GPU.Builder builderForValue) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.set(index, builderForValue.build());
          onChanged();
        } else {
          gpusBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder addGpus(com.protos.learn.sid.TestProcessorMessage.GPU value) {
        if (gpusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpusIsMutable();
          gpus_.add(value);
          onChanged();
        } else {
          gpusBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder addGpus(
          int index, com.protos.learn.sid.TestProcessorMessage.GPU value) {
        if (gpusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureGpusIsMutable();
          gpus_.add(index, value);
          onChanged();
        } else {
          gpusBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder addGpus(
          com.protos.learn.sid.TestProcessorMessage.GPU.Builder builderForValue) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.add(builderForValue.build());
          onChanged();
        } else {
          gpusBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder addGpus(
          int index, com.protos.learn.sid.TestProcessorMessage.GPU.Builder builderForValue) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.add(index, builderForValue.build());
          onChanged();
        } else {
          gpusBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder addAllGpus(
          java.lang.Iterable<? extends com.protos.learn.sid.TestProcessorMessage.GPU> values) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, gpus_);
          onChanged();
        } else {
          gpusBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder clearGpus() {
        if (gpusBuilder_ == null) {
          gpus_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          gpusBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public Builder removeGpus(int index) {
        if (gpusBuilder_ == null) {
          ensureGpusIsMutable();
          gpus_.remove(index);
          onChanged();
        } else {
          gpusBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.GPU.Builder getGpusBuilder(
          int index) {
        return getGpusFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder getGpusOrBuilder(
          int index) {
        if (gpusBuilder_ == null) {
          return gpus_.get(index);  } else {
          return gpusBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public java.util.List<? extends com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder> 
           getGpusOrBuilderList() {
        if (gpusBuilder_ != null) {
          return gpusBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(gpus_);
        }
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.GPU.Builder addGpusBuilder() {
        return getGpusFieldBuilder().addBuilder(
            com.protos.learn.sid.TestProcessorMessage.GPU.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public com.protos.learn.sid.TestProcessorMessage.GPU.Builder addGpusBuilder(
          int index) {
        return getGpusFieldBuilder().addBuilder(
            index, com.protos.learn.sid.TestProcessorMessage.GPU.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.learn.GPU gpus = 6;</code>
       */
      public java.util.List<com.protos.learn.sid.TestProcessorMessage.GPU.Builder> 
           getGpusBuilderList() {
        return getGpusFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.learn.sid.TestProcessorMessage.GPU, com.protos.learn.sid.TestProcessorMessage.GPU.Builder, com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder> 
          getGpusFieldBuilder() {
        if (gpusBuilder_ == null) {
          gpusBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protos.learn.sid.TestProcessorMessage.GPU, com.protos.learn.sid.TestProcessorMessage.GPU.Builder, com.protos.learn.sid.TestProcessorMessage.GPUOrBuilder>(
                  gpus_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          gpus_ = null;
        }
        return gpusBuilder_;
      }

      private java.util.List<com.protos.learn.sid.TestStorageMessage.Storage> storages_ =
        java.util.Collections.emptyList();
      private void ensureStoragesIsMutable() {
        if (!((bitField0_ & 0x00000040) == 0x00000040)) {
          storages_ = new java.util.ArrayList<com.protos.learn.sid.TestStorageMessage.Storage>(storages_);
          bitField0_ |= 0x00000040;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.learn.sid.TestStorageMessage.Storage, com.protos.learn.sid.TestStorageMessage.Storage.Builder, com.protos.learn.sid.TestStorageMessage.StorageOrBuilder> storagesBuilder_;

      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public java.util.List<com.protos.learn.sid.TestStorageMessage.Storage> getStoragesList() {
        if (storagesBuilder_ == null) {
          return java.util.Collections.unmodifiableList(storages_);
        } else {
          return storagesBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public int getStoragesCount() {
        if (storagesBuilder_ == null) {
          return storages_.size();
        } else {
          return storagesBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public com.protos.learn.sid.TestStorageMessage.Storage getStorages(int index) {
        if (storagesBuilder_ == null) {
          return storages_.get(index);
        } else {
          return storagesBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder setStorages(
          int index, com.protos.learn.sid.TestStorageMessage.Storage value) {
        if (storagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStoragesIsMutable();
          storages_.set(index, value);
          onChanged();
        } else {
          storagesBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder setStorages(
          int index, com.protos.learn.sid.TestStorageMessage.Storage.Builder builderForValue) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.set(index, builderForValue.build());
          onChanged();
        } else {
          storagesBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder addStorages(com.protos.learn.sid.TestStorageMessage.Storage value) {
        if (storagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStoragesIsMutable();
          storages_.add(value);
          onChanged();
        } else {
          storagesBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder addStorages(
          int index, com.protos.learn.sid.TestStorageMessage.Storage value) {
        if (storagesBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStoragesIsMutable();
          storages_.add(index, value);
          onChanged();
        } else {
          storagesBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder addStorages(
          com.protos.learn.sid.TestStorageMessage.Storage.Builder builderForValue) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.add(builderForValue.build());
          onChanged();
        } else {
          storagesBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder addStorages(
          int index, com.protos.learn.sid.TestStorageMessage.Storage.Builder builderForValue) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.add(index, builderForValue.build());
          onChanged();
        } else {
          storagesBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder addAllStorages(
          java.lang.Iterable<? extends com.protos.learn.sid.TestStorageMessage.Storage> values) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, storages_);
          onChanged();
        } else {
          storagesBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder clearStorages() {
        if (storagesBuilder_ == null) {
          storages_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000040);
          onChanged();
        } else {
          storagesBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public Builder removeStorages(int index) {
        if (storagesBuilder_ == null) {
          ensureStoragesIsMutable();
          storages_.remove(index);
          onChanged();
        } else {
          storagesBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public com.protos.learn.sid.TestStorageMessage.Storage.Builder getStoragesBuilder(
          int index) {
        return getStoragesFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public com.protos.learn.sid.TestStorageMessage.StorageOrBuilder getStoragesOrBuilder(
          int index) {
        if (storagesBuilder_ == null) {
          return storages_.get(index);  } else {
          return storagesBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public java.util.List<? extends com.protos.learn.sid.TestStorageMessage.StorageOrBuilder> 
           getStoragesOrBuilderList() {
        if (storagesBuilder_ != null) {
          return storagesBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(storages_);
        }
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public com.protos.learn.sid.TestStorageMessage.Storage.Builder addStoragesBuilder() {
        return getStoragesFieldBuilder().addBuilder(
            com.protos.learn.sid.TestStorageMessage.Storage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public com.protos.learn.sid.TestStorageMessage.Storage.Builder addStoragesBuilder(
          int index) {
        return getStoragesFieldBuilder().addBuilder(
            index, com.protos.learn.sid.TestStorageMessage.Storage.getDefaultInstance());
      }
      /**
       * <code>repeated .com.protos.learn.Storage storages = 7;</code>
       */
      public java.util.List<com.protos.learn.sid.TestStorageMessage.Storage.Builder> 
           getStoragesBuilderList() {
        return getStoragesFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.protos.learn.sid.TestStorageMessage.Storage, com.protos.learn.sid.TestStorageMessage.Storage.Builder, com.protos.learn.sid.TestStorageMessage.StorageOrBuilder> 
          getStoragesFieldBuilder() {
        if (storagesBuilder_ == null) {
          storagesBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.protos.learn.sid.TestStorageMessage.Storage, com.protos.learn.sid.TestStorageMessage.Storage.Builder, com.protos.learn.sid.TestStorageMessage.StorageOrBuilder>(
                  storages_,
                  ((bitField0_ & 0x00000040) == 0x00000040),
                  getParentForChildren(),
                  isClean());
          storages_ = null;
        }
        return storagesBuilder_;
      }

      private com.protos.learn.sid.TestScreenMessage.Screen screen_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestScreenMessage.Screen, com.protos.learn.sid.TestScreenMessage.Screen.Builder, com.protos.learn.sid.TestScreenMessage.ScreenOrBuilder> screenBuilder_;
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public boolean hasScreen() {
        return screenBuilder_ != null || screen_ != null;
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public com.protos.learn.sid.TestScreenMessage.Screen getScreen() {
        if (screenBuilder_ == null) {
          return screen_ == null ? com.protos.learn.sid.TestScreenMessage.Screen.getDefaultInstance() : screen_;
        } else {
          return screenBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public Builder setScreen(com.protos.learn.sid.TestScreenMessage.Screen value) {
        if (screenBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          screen_ = value;
          onChanged();
        } else {
          screenBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public Builder setScreen(
          com.protos.learn.sid.TestScreenMessage.Screen.Builder builderForValue) {
        if (screenBuilder_ == null) {
          screen_ = builderForValue.build();
          onChanged();
        } else {
          screenBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public Builder mergeScreen(com.protos.learn.sid.TestScreenMessage.Screen value) {
        if (screenBuilder_ == null) {
          if (screen_ != null) {
            screen_ =
              com.protos.learn.sid.TestScreenMessage.Screen.newBuilder(screen_).mergeFrom(value).buildPartial();
          } else {
            screen_ = value;
          }
          onChanged();
        } else {
          screenBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public Builder clearScreen() {
        if (screenBuilder_ == null) {
          screen_ = null;
          onChanged();
        } else {
          screen_ = null;
          screenBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public com.protos.learn.sid.TestScreenMessage.Screen.Builder getScreenBuilder() {
        
        onChanged();
        return getScreenFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      public com.protos.learn.sid.TestScreenMessage.ScreenOrBuilder getScreenOrBuilder() {
        if (screenBuilder_ != null) {
          return screenBuilder_.getMessageOrBuilder();
        } else {
          return screen_ == null ?
              com.protos.learn.sid.TestScreenMessage.Screen.getDefaultInstance() : screen_;
        }
      }
      /**
       * <code>.com.protos.learn.Screen screen = 8;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestScreenMessage.Screen, com.protos.learn.sid.TestScreenMessage.Screen.Builder, com.protos.learn.sid.TestScreenMessage.ScreenOrBuilder> 
          getScreenFieldBuilder() {
        if (screenBuilder_ == null) {
          screenBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.protos.learn.sid.TestScreenMessage.Screen, com.protos.learn.sid.TestScreenMessage.Screen.Builder, com.protos.learn.sid.TestScreenMessage.ScreenOrBuilder>(
                  getScreen(),
                  getParentForChildren(),
                  isClean());
          screen_ = null;
        }
        return screenBuilder_;
      }

      private com.protos.learn.sid.TestKeyboardMessage.Keyboard keyboard_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestKeyboardMessage.Keyboard, com.protos.learn.sid.TestKeyboardMessage.Keyboard.Builder, com.protos.learn.sid.TestKeyboardMessage.KeyboardOrBuilder> keyboardBuilder_;
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public boolean hasKeyboard() {
        return keyboardBuilder_ != null || keyboard_ != null;
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public com.protos.learn.sid.TestKeyboardMessage.Keyboard getKeyboard() {
        if (keyboardBuilder_ == null) {
          return keyboard_ == null ? com.protos.learn.sid.TestKeyboardMessage.Keyboard.getDefaultInstance() : keyboard_;
        } else {
          return keyboardBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public Builder setKeyboard(com.protos.learn.sid.TestKeyboardMessage.Keyboard value) {
        if (keyboardBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          keyboard_ = value;
          onChanged();
        } else {
          keyboardBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public Builder setKeyboard(
          com.protos.learn.sid.TestKeyboardMessage.Keyboard.Builder builderForValue) {
        if (keyboardBuilder_ == null) {
          keyboard_ = builderForValue.build();
          onChanged();
        } else {
          keyboardBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public Builder mergeKeyboard(com.protos.learn.sid.TestKeyboardMessage.Keyboard value) {
        if (keyboardBuilder_ == null) {
          if (keyboard_ != null) {
            keyboard_ =
              com.protos.learn.sid.TestKeyboardMessage.Keyboard.newBuilder(keyboard_).mergeFrom(value).buildPartial();
          } else {
            keyboard_ = value;
          }
          onChanged();
        } else {
          keyboardBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public Builder clearKeyboard() {
        if (keyboardBuilder_ == null) {
          keyboard_ = null;
          onChanged();
        } else {
          keyboard_ = null;
          keyboardBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public com.protos.learn.sid.TestKeyboardMessage.Keyboard.Builder getKeyboardBuilder() {
        
        onChanged();
        return getKeyboardFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      public com.protos.learn.sid.TestKeyboardMessage.KeyboardOrBuilder getKeyboardOrBuilder() {
        if (keyboardBuilder_ != null) {
          return keyboardBuilder_.getMessageOrBuilder();
        } else {
          return keyboard_ == null ?
              com.protos.learn.sid.TestKeyboardMessage.Keyboard.getDefaultInstance() : keyboard_;
        }
      }
      /**
       * <code>.com.protos.learn.Keyboard keyboard = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestKeyboardMessage.Keyboard, com.protos.learn.sid.TestKeyboardMessage.Keyboard.Builder, com.protos.learn.sid.TestKeyboardMessage.KeyboardOrBuilder> 
          getKeyboardFieldBuilder() {
        if (keyboardBuilder_ == null) {
          keyboardBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.protos.learn.sid.TestKeyboardMessage.Keyboard, com.protos.learn.sid.TestKeyboardMessage.Keyboard.Builder, com.protos.learn.sid.TestKeyboardMessage.KeyboardOrBuilder>(
                  getKeyboard(),
                  getParentForChildren(),
                  isClean());
          keyboard_ = null;
        }
        return keyboardBuilder_;
      }

      /**
       * <code>double weight_kg = 10;</code>
       */
      public double getWeightKg() {
        if (weightCase_ == 10) {
          return (java.lang.Double) weight_;
        }
        return 0D;
      }
      /**
       * <code>double weight_kg = 10;</code>
       */
      public Builder setWeightKg(double value) {
        weightCase_ = 10;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight_kg = 10;</code>
       */
      public Builder clearWeightKg() {
        if (weightCase_ == 10) {
          weightCase_ = 0;
          weight_ = null;
          onChanged();
        }
        return this;
      }

      /**
       * <code>double weight_lb = 11;</code>
       */
      public double getWeightLb() {
        if (weightCase_ == 11) {
          return (java.lang.Double) weight_;
        }
        return 0D;
      }
      /**
       * <code>double weight_lb = 11;</code>
       */
      public Builder setWeightLb(double value) {
        weightCase_ = 11;
        weight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double weight_lb = 11;</code>
       */
      public Builder clearWeightLb() {
        if (weightCase_ == 11) {
          weightCase_ = 0;
          weight_ = null;
          onChanged();
        }
        return this;
      }

      private double priceUsd_ ;
      /**
       * <code>double price_usd = 12;</code>
       */
      public double getPriceUsd() {
        return priceUsd_;
      }
      /**
       * <code>double price_usd = 12;</code>
       */
      public Builder setPriceUsd(double value) {
        
        priceUsd_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double price_usd = 12;</code>
       */
      public Builder clearPriceUsd() {
        
        priceUsd_ = 0D;
        onChanged();
        return this;
      }

      private int releaseYear_ ;
      /**
       * <code>uint32 release_year = 13;</code>
       */
      public int getReleaseYear() {
        return releaseYear_;
      }
      /**
       * <code>uint32 release_year = 13;</code>
       */
      public Builder setReleaseYear(int value) {
        
        releaseYear_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 release_year = 13;</code>
       */
      public Builder clearReleaseYear() {
        
        releaseYear_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp updatedAt_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> updatedAtBuilder_;
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public boolean hasUpdatedAt() {
        return updatedAtBuilder_ != null || updatedAt_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public com.google.protobuf.Timestamp getUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          return updatedAt_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        } else {
          return updatedAtBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder setUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          updatedAt_ = value;
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder setUpdatedAt(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = builderForValue.build();
          onChanged();
        } else {
          updatedAtBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder mergeUpdatedAt(com.google.protobuf.Timestamp value) {
        if (updatedAtBuilder_ == null) {
          if (updatedAt_ != null) {
            updatedAt_ =
              com.google.protobuf.Timestamp.newBuilder(updatedAt_).mergeFrom(value).buildPartial();
          } else {
            updatedAt_ = value;
          }
          onChanged();
        } else {
          updatedAtBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public Builder clearUpdatedAt() {
        if (updatedAtBuilder_ == null) {
          updatedAt_ = null;
          onChanged();
        } else {
          updatedAt_ = null;
          updatedAtBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public com.google.protobuf.Timestamp.Builder getUpdatedAtBuilder() {
        
        onChanged();
        return getUpdatedAtFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getUpdatedAtOrBuilder() {
        if (updatedAtBuilder_ != null) {
          return updatedAtBuilder_.getMessageOrBuilder();
        } else {
          return updatedAt_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : updatedAt_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp updated_at = 14;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getUpdatedAtFieldBuilder() {
        if (updatedAtBuilder_ == null) {
          updatedAtBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getUpdatedAt(),
                  getParentForChildren(),
                  isClean());
          updatedAt_ = null;
        }
        return updatedAtBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protos.learn.Laptop)
    }

    // @@protoc_insertion_point(class_scope:com.protos.learn.Laptop)
    private static final com.protos.learn.sid.TestLaptopMessage.Laptop DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.learn.sid.TestLaptopMessage.Laptop();
    }

    public static com.protos.learn.sid.TestLaptopMessage.Laptop getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Laptop>
        PARSER = new com.google.protobuf.AbstractParser<Laptop>() {
      @java.lang.Override
      public Laptop parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Laptop(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Laptop> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Laptop> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protos.learn.sid.TestLaptopMessage.Laptop getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_Laptop_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_Laptop_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031test_laptop_message.proto\022\020com.protos." +
      "learn\032\034test_processor_message.proto\032\031tes" +
      "t_memory_message.proto\032\032test_storage_mes" +
      "sage.proto\032\031test_screen_message.proto\032\033t" +
      "est_keyboard_message.proto\032\037google/proto" +
      "buf/timestamp.proto\"\263\003\n\006Laptop\022\n\n\002id\030\001 \001" +
      "(\t\022\r\n\005brand\030\002 \001(\t\022\014\n\004name\030\003 \001(\t\022\"\n\003cpu\030\004" +
      " \001(\0132\025.com.protos.learn.CPU\022%\n\003ram\030\005 \001(\013" +
      "2\030.com.protos.learn.Memory\022#\n\004gpus\030\006 \003(\013" +
      "2\025.com.protos.learn.GPU\022+\n\010storages\030\007 \003(" +
      "\0132\031.com.protos.learn.Storage\022(\n\006screen\030\010" +
      " \001(\0132\030.com.protos.learn.Screen\022,\n\010keyboa" +
      "rd\030\t \001(\0132\032.com.protos.learn.Keyboard\022\023\n\t" +
      "weight_kg\030\n \001(\001H\000\022\023\n\tweight_lb\030\013 \001(\001H\000\022\021" +
      "\n\tprice_usd\030\014 \001(\001\022\024\n\014release_year\030\r \001(\r\022" +
      ".\n\nupdated_at\030\016 \001(\0132\032.google.protobuf.Ti" +
      "mestampB\010\n\006weightB\026\n\024com.protos.learn.si" +
      "db\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.protos.learn.sid.TestProcessorMessage.getDescriptor(),
          com.protos.learn.sid.TestMemoryMessage.getDescriptor(),
          com.protos.learn.sid.TestStorageMessage.getDescriptor(),
          com.protos.learn.sid.TestScreenMessage.getDescriptor(),
          com.protos.learn.sid.TestKeyboardMessage.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        }, assigner);
    internal_static_com_protos_learn_Laptop_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_learn_Laptop_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_Laptop_descriptor,
        new java.lang.String[] { "Id", "Brand", "Name", "Cpu", "Ram", "Gpus", "Storages", "Screen", "Keyboard", "WeightKg", "WeightLb", "PriceUsd", "ReleaseYear", "UpdatedAt", "Weight", });
    com.protos.learn.sid.TestProcessorMessage.getDescriptor();
    com.protos.learn.sid.TestMemoryMessage.getDescriptor();
    com.protos.learn.sid.TestStorageMessage.getDescriptor();
    com.protos.learn.sid.TestScreenMessage.getDescriptor();
    com.protos.learn.sid.TestKeyboardMessage.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
