// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test_screen_message.proto

package com.protos.learn.sid;

public final class TestScreenMessage {
  private TestScreenMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ScreenOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.protos.learn.Screen)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float size_inch = 1;</code>
     */
    float getSizeInch();

    /**
     * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
     */
    boolean hasResolution();
    /**
     * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
     */
    com.protos.learn.sid.TestScreenMessage.Screen.Resolution getResolution();
    /**
     * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
     */
    com.protos.learn.sid.TestScreenMessage.Screen.ResolutionOrBuilder getResolutionOrBuilder();

    /**
     * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
     */
    int getPanelValue();
    /**
     * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
     */
    com.protos.learn.sid.TestScreenMessage.Screen.Panel getPanel();

    /**
     * <code>bool multitouch = 4;</code>
     */
    boolean getMultitouch();
  }
  /**
   * Protobuf type {@code com.protos.learn.Screen}
   */
  public  static final class Screen extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.protos.learn.Screen)
      ScreenOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Screen.newBuilder() to construct.
    private Screen(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Screen() {
      sizeInch_ = 0F;
      panel_ = 0;
      multitouch_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Screen(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              sizeInch_ = input.readFloat();
              break;
            }
            case 18: {
              com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder subBuilder = null;
              if (resolution_ != null) {
                subBuilder = resolution_.toBuilder();
              }
              resolution_ = input.readMessage(com.protos.learn.sid.TestScreenMessage.Screen.Resolution.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(resolution_);
                resolution_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              panel_ = rawValue;
              break;
            }
            case 32: {

              multitouch_ = input.readBool();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.protos.learn.sid.TestScreenMessage.Screen.class, com.protos.learn.sid.TestScreenMessage.Screen.Builder.class);
    }

    /**
     * Protobuf enum {@code com.protos.learn.Screen.Panel}
     */
    public enum Panel
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>UNKNOWN = 0;</code>
       */
      UNKNOWN(0),
      /**
       * <code>IPS = 1;</code>
       */
      IPS(1),
      /**
       * <code>OLED = 2;</code>
       */
      OLED(2),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>UNKNOWN = 0;</code>
       */
      public static final int UNKNOWN_VALUE = 0;
      /**
       * <code>IPS = 1;</code>
       */
      public static final int IPS_VALUE = 1;
      /**
       * <code>OLED = 2;</code>
       */
      public static final int OLED_VALUE = 2;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Panel valueOf(int value) {
        return forNumber(value);
      }

      public static Panel forNumber(int value) {
        switch (value) {
          case 0: return UNKNOWN;
          case 1: return IPS;
          case 2: return OLED;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Panel>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Panel> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Panel>() {
              public Panel findValueByNumber(int number) {
                return Panel.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return com.protos.learn.sid.TestScreenMessage.Screen.getDescriptor().getEnumTypes().get(0);
      }

      private static final Panel[] VALUES = values();

      public static Panel valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Panel(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:com.protos.learn.Screen.Panel)
    }

    public interface ResolutionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.protos.learn.Screen.Resolution)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>uint32 width = 1;</code>
       */
      int getWidth();

      /**
       * <code>uint32 height = 2;</code>
       */
      int getHeight();
    }
    /**
     * Protobuf type {@code com.protos.learn.Screen.Resolution}
     */
    public  static final class Resolution extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.protos.learn.Screen.Resolution)
        ResolutionOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Resolution.newBuilder() to construct.
      private Resolution(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Resolution() {
        width_ = 0;
        height_ = 0;
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Resolution(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {

                width_ = input.readUInt32();
                break;
              }
              case 16: {

                height_ = input.readUInt32();
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_Resolution_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_Resolution_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.learn.sid.TestScreenMessage.Screen.Resolution.class, com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder.class);
      }

      public static final int WIDTH_FIELD_NUMBER = 1;
      private int width_;
      /**
       * <code>uint32 width = 1;</code>
       */
      public int getWidth() {
        return width_;
      }

      public static final int HEIGHT_FIELD_NUMBER = 2;
      private int height_;
      /**
       * <code>uint32 height = 2;</code>
       */
      public int getHeight() {
        return height_;
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (width_ != 0) {
          output.writeUInt32(1, width_);
        }
        if (height_ != 0) {
          output.writeUInt32(2, height_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (width_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(1, width_);
        }
        if (height_ != 0) {
          size += com.google.protobuf.CodedOutputStream
            .computeUInt32Size(2, height_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.protos.learn.sid.TestScreenMessage.Screen.Resolution)) {
          return super.equals(obj);
        }
        com.protos.learn.sid.TestScreenMessage.Screen.Resolution other = (com.protos.learn.sid.TestScreenMessage.Screen.Resolution) obj;

        boolean result = true;
        result = result && (getWidth()
            == other.getWidth());
        result = result && (getHeight()
            == other.getHeight());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + WIDTH_FIELD_NUMBER;
        hash = (53 * hash) + getWidth();
        hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
        hash = (53 * hash) + getHeight();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.protos.learn.sid.TestScreenMessage.Screen.Resolution prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.protos.learn.Screen.Resolution}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.protos.learn.Screen.Resolution)
          com.protos.learn.sid.TestScreenMessage.Screen.ResolutionOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_Resolution_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_Resolution_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.protos.learn.sid.TestScreenMessage.Screen.Resolution.class, com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder.class);
        }

        // Construct using com.protos.learn.sid.TestScreenMessage.Screen.Resolution.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          width_ = 0;

          height_ = 0;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_Resolution_descriptor;
        }

        @java.lang.Override
        public com.protos.learn.sid.TestScreenMessage.Screen.Resolution getDefaultInstanceForType() {
          return com.protos.learn.sid.TestScreenMessage.Screen.Resolution.getDefaultInstance();
        }

        @java.lang.Override
        public com.protos.learn.sid.TestScreenMessage.Screen.Resolution build() {
          com.protos.learn.sid.TestScreenMessage.Screen.Resolution result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.protos.learn.sid.TestScreenMessage.Screen.Resolution buildPartial() {
          com.protos.learn.sid.TestScreenMessage.Screen.Resolution result = new com.protos.learn.sid.TestScreenMessage.Screen.Resolution(this);
          result.width_ = width_;
          result.height_ = height_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.protos.learn.sid.TestScreenMessage.Screen.Resolution) {
            return mergeFrom((com.protos.learn.sid.TestScreenMessage.Screen.Resolution)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.protos.learn.sid.TestScreenMessage.Screen.Resolution other) {
          if (other == com.protos.learn.sid.TestScreenMessage.Screen.Resolution.getDefaultInstance()) return this;
          if (other.getWidth() != 0) {
            setWidth(other.getWidth());
          }
          if (other.getHeight() != 0) {
            setHeight(other.getHeight());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.protos.learn.sid.TestScreenMessage.Screen.Resolution parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.protos.learn.sid.TestScreenMessage.Screen.Resolution) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private int width_ ;
        /**
         * <code>uint32 width = 1;</code>
         */
        public int getWidth() {
          return width_;
        }
        /**
         * <code>uint32 width = 1;</code>
         */
        public Builder setWidth(int value) {
          
          width_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 width = 1;</code>
         */
        public Builder clearWidth() {
          
          width_ = 0;
          onChanged();
          return this;
        }

        private int height_ ;
        /**
         * <code>uint32 height = 2;</code>
         */
        public int getHeight() {
          return height_;
        }
        /**
         * <code>uint32 height = 2;</code>
         */
        public Builder setHeight(int value) {
          
          height_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>uint32 height = 2;</code>
         */
        public Builder clearHeight() {
          
          height_ = 0;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.protos.learn.Screen.Resolution)
      }

      // @@protoc_insertion_point(class_scope:com.protos.learn.Screen.Resolution)
      private static final com.protos.learn.sid.TestScreenMessage.Screen.Resolution DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.protos.learn.sid.TestScreenMessage.Screen.Resolution();
      }

      public static com.protos.learn.sid.TestScreenMessage.Screen.Resolution getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Resolution>
          PARSER = new com.google.protobuf.AbstractParser<Resolution>() {
        @java.lang.Override
        public Resolution parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Resolution(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Resolution> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Resolution> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestScreenMessage.Screen.Resolution getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int SIZE_INCH_FIELD_NUMBER = 1;
    private float sizeInch_;
    /**
     * <code>float size_inch = 1;</code>
     */
    public float getSizeInch() {
      return sizeInch_;
    }

    public static final int RESOLUTION_FIELD_NUMBER = 2;
    private com.protos.learn.sid.TestScreenMessage.Screen.Resolution resolution_;
    /**
     * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
     */
    public boolean hasResolution() {
      return resolution_ != null;
    }
    /**
     * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
     */
    public com.protos.learn.sid.TestScreenMessage.Screen.Resolution getResolution() {
      return resolution_ == null ? com.protos.learn.sid.TestScreenMessage.Screen.Resolution.getDefaultInstance() : resolution_;
    }
    /**
     * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
     */
    public com.protos.learn.sid.TestScreenMessage.Screen.ResolutionOrBuilder getResolutionOrBuilder() {
      return getResolution();
    }

    public static final int PANEL_FIELD_NUMBER = 3;
    private int panel_;
    /**
     * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
     */
    public int getPanelValue() {
      return panel_;
    }
    /**
     * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
     */
    public com.protos.learn.sid.TestScreenMessage.Screen.Panel getPanel() {
      @SuppressWarnings("deprecation")
      com.protos.learn.sid.TestScreenMessage.Screen.Panel result = com.protos.learn.sid.TestScreenMessage.Screen.Panel.valueOf(panel_);
      return result == null ? com.protos.learn.sid.TestScreenMessage.Screen.Panel.UNRECOGNIZED : result;
    }

    public static final int MULTITOUCH_FIELD_NUMBER = 4;
    private boolean multitouch_;
    /**
     * <code>bool multitouch = 4;</code>
     */
    public boolean getMultitouch() {
      return multitouch_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (sizeInch_ != 0F) {
        output.writeFloat(1, sizeInch_);
      }
      if (resolution_ != null) {
        output.writeMessage(2, getResolution());
      }
      if (panel_ != com.protos.learn.sid.TestScreenMessage.Screen.Panel.UNKNOWN.getNumber()) {
        output.writeEnum(3, panel_);
      }
      if (multitouch_ != false) {
        output.writeBool(4, multitouch_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (sizeInch_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, sizeInch_);
      }
      if (resolution_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getResolution());
      }
      if (panel_ != com.protos.learn.sid.TestScreenMessage.Screen.Panel.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, panel_);
      }
      if (multitouch_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, multitouch_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.protos.learn.sid.TestScreenMessage.Screen)) {
        return super.equals(obj);
      }
      com.protos.learn.sid.TestScreenMessage.Screen other = (com.protos.learn.sid.TestScreenMessage.Screen) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getSizeInch())
          == java.lang.Float.floatToIntBits(
              other.getSizeInch()));
      result = result && (hasResolution() == other.hasResolution());
      if (hasResolution()) {
        result = result && getResolution()
            .equals(other.getResolution());
      }
      result = result && panel_ == other.panel_;
      result = result && (getMultitouch()
          == other.getMultitouch());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SIZE_INCH_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getSizeInch());
      if (hasResolution()) {
        hash = (37 * hash) + RESOLUTION_FIELD_NUMBER;
        hash = (53 * hash) + getResolution().hashCode();
      }
      hash = (37 * hash) + PANEL_FIELD_NUMBER;
      hash = (53 * hash) + panel_;
      hash = (37 * hash) + MULTITOUCH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getMultitouch());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.protos.learn.sid.TestScreenMessage.Screen parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.protos.learn.sid.TestScreenMessage.Screen prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.protos.learn.Screen}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.protos.learn.Screen)
        com.protos.learn.sid.TestScreenMessage.ScreenOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.protos.learn.sid.TestScreenMessage.Screen.class, com.protos.learn.sid.TestScreenMessage.Screen.Builder.class);
      }

      // Construct using com.protos.learn.sid.TestScreenMessage.Screen.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        sizeInch_ = 0F;

        if (resolutionBuilder_ == null) {
          resolution_ = null;
        } else {
          resolution_ = null;
          resolutionBuilder_ = null;
        }
        panel_ = 0;

        multitouch_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.protos.learn.sid.TestScreenMessage.internal_static_com_protos_learn_Screen_descriptor;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestScreenMessage.Screen getDefaultInstanceForType() {
        return com.protos.learn.sid.TestScreenMessage.Screen.getDefaultInstance();
      }

      @java.lang.Override
      public com.protos.learn.sid.TestScreenMessage.Screen build() {
        com.protos.learn.sid.TestScreenMessage.Screen result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.protos.learn.sid.TestScreenMessage.Screen buildPartial() {
        com.protos.learn.sid.TestScreenMessage.Screen result = new com.protos.learn.sid.TestScreenMessage.Screen(this);
        result.sizeInch_ = sizeInch_;
        if (resolutionBuilder_ == null) {
          result.resolution_ = resolution_;
        } else {
          result.resolution_ = resolutionBuilder_.build();
        }
        result.panel_ = panel_;
        result.multitouch_ = multitouch_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.protos.learn.sid.TestScreenMessage.Screen) {
          return mergeFrom((com.protos.learn.sid.TestScreenMessage.Screen)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.protos.learn.sid.TestScreenMessage.Screen other) {
        if (other == com.protos.learn.sid.TestScreenMessage.Screen.getDefaultInstance()) return this;
        if (other.getSizeInch() != 0F) {
          setSizeInch(other.getSizeInch());
        }
        if (other.hasResolution()) {
          mergeResolution(other.getResolution());
        }
        if (other.panel_ != 0) {
          setPanelValue(other.getPanelValue());
        }
        if (other.getMultitouch() != false) {
          setMultitouch(other.getMultitouch());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.protos.learn.sid.TestScreenMessage.Screen parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.protos.learn.sid.TestScreenMessage.Screen) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float sizeInch_ ;
      /**
       * <code>float size_inch = 1;</code>
       */
      public float getSizeInch() {
        return sizeInch_;
      }
      /**
       * <code>float size_inch = 1;</code>
       */
      public Builder setSizeInch(float value) {
        
        sizeInch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float size_inch = 1;</code>
       */
      public Builder clearSizeInch() {
        
        sizeInch_ = 0F;
        onChanged();
        return this;
      }

      private com.protos.learn.sid.TestScreenMessage.Screen.Resolution resolution_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestScreenMessage.Screen.Resolution, com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder, com.protos.learn.sid.TestScreenMessage.Screen.ResolutionOrBuilder> resolutionBuilder_;
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public boolean hasResolution() {
        return resolutionBuilder_ != null || resolution_ != null;
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public com.protos.learn.sid.TestScreenMessage.Screen.Resolution getResolution() {
        if (resolutionBuilder_ == null) {
          return resolution_ == null ? com.protos.learn.sid.TestScreenMessage.Screen.Resolution.getDefaultInstance() : resolution_;
        } else {
          return resolutionBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public Builder setResolution(com.protos.learn.sid.TestScreenMessage.Screen.Resolution value) {
        if (resolutionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          resolution_ = value;
          onChanged();
        } else {
          resolutionBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public Builder setResolution(
          com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder builderForValue) {
        if (resolutionBuilder_ == null) {
          resolution_ = builderForValue.build();
          onChanged();
        } else {
          resolutionBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public Builder mergeResolution(com.protos.learn.sid.TestScreenMessage.Screen.Resolution value) {
        if (resolutionBuilder_ == null) {
          if (resolution_ != null) {
            resolution_ =
              com.protos.learn.sid.TestScreenMessage.Screen.Resolution.newBuilder(resolution_).mergeFrom(value).buildPartial();
          } else {
            resolution_ = value;
          }
          onChanged();
        } else {
          resolutionBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public Builder clearResolution() {
        if (resolutionBuilder_ == null) {
          resolution_ = null;
          onChanged();
        } else {
          resolution_ = null;
          resolutionBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder getResolutionBuilder() {
        
        onChanged();
        return getResolutionFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      public com.protos.learn.sid.TestScreenMessage.Screen.ResolutionOrBuilder getResolutionOrBuilder() {
        if (resolutionBuilder_ != null) {
          return resolutionBuilder_.getMessageOrBuilder();
        } else {
          return resolution_ == null ?
              com.protos.learn.sid.TestScreenMessage.Screen.Resolution.getDefaultInstance() : resolution_;
        }
      }
      /**
       * <code>.com.protos.learn.Screen.Resolution resolution = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.protos.learn.sid.TestScreenMessage.Screen.Resolution, com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder, com.protos.learn.sid.TestScreenMessage.Screen.ResolutionOrBuilder> 
          getResolutionFieldBuilder() {
        if (resolutionBuilder_ == null) {
          resolutionBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.protos.learn.sid.TestScreenMessage.Screen.Resolution, com.protos.learn.sid.TestScreenMessage.Screen.Resolution.Builder, com.protos.learn.sid.TestScreenMessage.Screen.ResolutionOrBuilder>(
                  getResolution(),
                  getParentForChildren(),
                  isClean());
          resolution_ = null;
        }
        return resolutionBuilder_;
      }

      private int panel_ = 0;
      /**
       * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
       */
      public int getPanelValue() {
        return panel_;
      }
      /**
       * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
       */
      public Builder setPanelValue(int value) {
        panel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
       */
      public com.protos.learn.sid.TestScreenMessage.Screen.Panel getPanel() {
        @SuppressWarnings("deprecation")
        com.protos.learn.sid.TestScreenMessage.Screen.Panel result = com.protos.learn.sid.TestScreenMessage.Screen.Panel.valueOf(panel_);
        return result == null ? com.protos.learn.sid.TestScreenMessage.Screen.Panel.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
       */
      public Builder setPanel(com.protos.learn.sid.TestScreenMessage.Screen.Panel value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        panel_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.protos.learn.Screen.Panel panel = 3;</code>
       */
      public Builder clearPanel() {
        
        panel_ = 0;
        onChanged();
        return this;
      }

      private boolean multitouch_ ;
      /**
       * <code>bool multitouch = 4;</code>
       */
      public boolean getMultitouch() {
        return multitouch_;
      }
      /**
       * <code>bool multitouch = 4;</code>
       */
      public Builder setMultitouch(boolean value) {
        
        multitouch_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool multitouch = 4;</code>
       */
      public Builder clearMultitouch() {
        
        multitouch_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.protos.learn.Screen)
    }

    // @@protoc_insertion_point(class_scope:com.protos.learn.Screen)
    private static final com.protos.learn.sid.TestScreenMessage.Screen DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.protos.learn.sid.TestScreenMessage.Screen();
    }

    public static com.protos.learn.sid.TestScreenMessage.Screen getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Screen>
        PARSER = new com.google.protobuf.AbstractParser<Screen>() {
      @java.lang.Override
      public Screen parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Screen(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Screen> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Screen> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.protos.learn.sid.TestScreenMessage.Screen getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_Screen_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_Screen_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_protos_learn_Screen_Resolution_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_protos_learn_Screen_Resolution_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031test_screen_message.proto\022\020com.protos." +
      "learn\"\355\001\n\006Screen\022\021\n\tsize_inch\030\001 \001(\002\0227\n\nr" +
      "esolution\030\002 \001(\0132#.com.protos.learn.Scree" +
      "n.Resolution\022-\n\005panel\030\003 \001(\0162\036.com.protos" +
      ".learn.Screen.Panel\022\022\n\nmultitouch\030\004 \001(\010\032" +
      "+\n\nResolution\022\r\n\005width\030\001 \001(\r\022\016\n\006height\030\002" +
      " \001(\r\"\'\n\005Panel\022\013\n\007UNKNOWN\020\000\022\007\n\003IPS\020\001\022\010\n\004O" +
      "LED\020\002B\026\n\024com.protos.learn.sidb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_protos_learn_Screen_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_protos_learn_Screen_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_Screen_descriptor,
        new java.lang.String[] { "SizeInch", "Resolution", "Panel", "Multitouch", });
    internal_static_com_protos_learn_Screen_Resolution_descriptor =
      internal_static_com_protos_learn_Screen_descriptor.getNestedTypes().get(0);
    internal_static_com_protos_learn_Screen_Resolution_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_protos_learn_Screen_Resolution_descriptor,
        new java.lang.String[] { "Width", "Height", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
